syntax = "proto3";

package infra_service.v1;
import "google/protobuf/empty.proto";

enum Status {
        SUCCESS = 0;
        FAILED = 1;
        DUPLICATE = 2;
        USER_NOT_FOUND = 3;
        PASSWORD_REQ_FAILED = 4;
        UNKNOWN = 5;
        SHARE_NOT_FOUND = 6;
}

message AddDomainUserData {
        string username = 1;
        string password = 2;
}

message AddDomainUserDataAck {
        Status status   = 1;
        string result   = 2;
}

message RemoveDomainUserData {
        string username = 1;
}

message RemoveDomainUserDataAck {
        Status status   = 1;
        string result   = 2;
}

message CreateSambaFileShareData {
        string share_name = 1;
}

message CreateSambaFileShareDataAck {
        Status status = 1;
}

message RestartSambaServiceDataAck {
        Status status = 1;
}

message ResetUserPasswordData {
        string username = 1;
        string password = 2;
}

message ResetUserPasswordDataAck {
        Status status = 1;
}

message GetUserListDataAck {
        Status status = 1;
        repeated string users = 2;
}

message GetFileShareSizeData {
        string share_name = 1;
}

message GetFileShareSizeDataAck {
        int32 total_size = 1;
        int32 usage_size = 2;
}

message DeleteSambaFileShareData {
        string share_name = 1;
        bool wipe_data = 2;
}

message DeleteSambaFileShareDataAck {
        Status status = 1;
}

service InfraService {
        rpc GetUserList(google.protobuf.Empty) returns (GetUserListDataAck);
        rpc RestartSambaService(google.protobuf.Empty) returns (RestartSambaServiceDataAck);
        rpc CreateSambaFileShare(CreateSambaFileShareData) returns (CreateSambaFileShareDataAck);
        rpc DeleteSambaFileShare(DeleteSambaFileShareData) returns (DeleteSambaFileShareDataAck);
        rpc ResetUserPassword(ResetUserPasswordData) returns (ResetUserPasswordDataAck);
        rpc AddDomainUser(AddDomainUserData) returns (AddDomainUserDataAck);
        rpc RemoveDomainUser(RemoveDomainUserData) returns (RemoveDomainUserDataAck);
        rpc GetFileShareSize(GetFileShareSizeData) returns (GetFileShareSizeDataAck);
}
