syntax = "proto3";

message Process {
  int32 pid = 1;
  string name = 2;
  string exe = 3;
  string username = 4;
  string cpu_percent = 5;
  string memory_usage = 6;
  string create_time = 7;
  string cmdline = 8;
  int32 ppid = 9;
}

message ProcessList {
  string agent_id = 1;
  int64 timestamp = 2;
  repeated Process processes = 3;
}


message WorkstationInit {
        string agent_id = 1;
        string domain = 2;
}

message Ack {
  bool success = 1;
  string message = 2;
}

message ProcessInformation {
	int32 pid = 1;
	string name = 2;
        repeated string handles = 3;
}


message ProcessListAckRes {
	string agent_id = 1;
	int64 timestamp = 2;
	repeated ProcessInformation processes = 3;
}

message ProcessListAck {
	bool action = 1;
	repeated int32 pids = 2;
}

service AgentService {
	rpc SendProcessList(ProcessList) returns (ProcessListAck);
	rpc SendProcessListInformation(ProcessListAckRes) returns (Ack);

	rpc SendWorkstationInit(WorkstationInit) returns (Ack);
}
