services:
  redis:
    image: redis:7
    command: ["redis-server", "--stop-writes-on-bgsave-error", "no"]
    ports:
      - "6379:6379"
    networks:
      vpc_net: 
        ipv4_address: 172.23.0.5
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: cs-api
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - MONGO_URL=${MONGO_URL}
      - MONGO_DB=${MONGO_DB}
    depends_on:
      - redis
    ports:
      - "5050:5050"
    volumes:
      - ./logs:/app/logs

  openvpn-test:
    build:
      context: .
      dockerfile: docker/Dockerfile.openvpn_test
    privileged: true
    cgroup: host
    tty: true
    stdin_open: true
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - openvpn_port=${OPENVPN_PORT}
      - openvpn_protocol=${OPENVPN_PROTOCOL}
      - openvpn_client_name=${OPENVPN_CLIENT_NAME}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      vpc_net:
        ipv4_address: 172.23.0.12


    
  samba-test:
    build:
      context: .
      args:
        - ORG_ID=${DOMAIN_NAME}
      dockerfile: docker/Dockerfile.samba_test
    container_name: cs-samba-test
    privileged: true
    cgroup: host
    tty: true
    stdin_open: true
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    environment:
      - domain_name=${DOMAIN_NAME}
      - dc_admin_password=${DC_ADMIN_PASSWORD}
      - realm_name=${REALM_NAME}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      vpc_net:
        ipv4_address: 172.23.0.10

  api-test:
    build:
      context: .
      dockerfile: docker/Dockerfile.api_test
    container_name: cs-api-test
    environment:
      - MONGO_URL=${MONGO_URL}
      - MONGO_DB=${MONGO_DB}
      - CLOUDSHIELD_DEV_TOKEN=${CLOUDSHIELD_DEV_TOKEN}
      - CLOUDSHIELD_DEV_EMAIL=${CLOUDSHIELD_DEV_EMAIL}
      - CLOUDSHIELD_DEV_ROLE=${CLOUDSHIELD_DEV_ROLE}
      - CLOUDSHIELD_DEV_ORG=${CLOUDSHIELD_DEV_ORG}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - redis
    ports:
      - "5050:5050"
    networks: # for a dev env we will pretent that the API has access to the VPC somehow
      - vpc_net
    volumes:
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      cloudshield_net:
        ipv4_address: 172.28.0.5
    ports:
      - "9200:9200"

  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    container_name: server
    environment:
      ES_URL: "http://elasticsearch:9200"
      CLOUDSHIELD_RUNTIME: "1"
    networks:
      cloudshield_net:
        ipv4_address: 172.28.0.10
    ports:
      - "50051:50051"

  agent1:
    build:
      context: .
      dockerfile: docker/Dockerfile.agent
    container_name: agent1
    environment:
      AGENT_ID: "agent-1"
      SERVER_ADDR: "server"
      SERVER_PORT: "50051"
    depends_on:
      - server
    networks:
      cloudshield_net:
        ipv4_address: 172.28.0.11

  agent2:
    build:
      context: .
      dockerfile: docker/Dockerfile.agent
    container_name: agent2
    environment:
      AGENT_ID: "agent-2"
      SERVER_ADDR: "server"
      SERVER_PORT: "50051"
    depends_on:
      - server
    networks:
      cloudshield_net:
        ipv4_address: 172.28.0.12

  agent3:
    build:
      context: .
      dockerfile: docker/Dockerfile.agent
    container_name: agent3
    environment:
      AGENT_ID: "agent-3"
      SERVER_ADDR: "server"
      SERVER_PORT: "50051"
    depends_on:
      - server
    networks:
      cloudshield_net:
        ipv4_address: 172.28.0.13

  ui:
    build:
      context: .                # path to your UI project (you were in WebUI %)
      dockerfile: docker/Dockerfile.ui
    container_name: cs-ui
    environment:
      - VITE_PORT=5173
      - CHOKIDAR_USEPOLLING=true       # improves hot-reload on Docker Desktop
      - VITE_API_ACCESS_TOKEN=${VITE_API_ACCESS_TOKEN}
    networks:
      cloudshield_net:
        ipv4_address: 172.28.0.20
    ports:
      - "5173:5173"                    # Vite dev server
    volumes:
      - ./cloudshield/WebUI:/app                   # live reload your source
      - ui_node_modules:/app/node_modules

networks:
  vpc_net:
    external: true
    driver: bridge
    ipam:
      driver: bridge
      config:
        - subnet: 172.25.0.0/24
  cloudshield_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  ui_node_modules:
