line-length = 100
target-version = "py311"

[lint]
select = ["E", "F"]

[lint.per-file-ignores]
"cloudshield/Agent/core/__init__.py" = ["F401"]
"cloudshield/Agent/tasks/__init__.py" = ["F401"]
"cloudshield/Agent/proto/*" = ["F401", "F541"]
"cloudshield/Server/tasks.py" = ["F401", "F541"]
"cloudshield/Agent/tasks/task.py" = ["F401"]
