FROM ubuntu:latest

# This dockerfile will mimic a cloud provisioned samba ad dc

# Prevent interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Install required packages
RUN apt-get update && \
    apt-get install -qq -y --no-install-recommends \
      samba-ad-dc samba-ad-provision systemd krb5-user bind9-dnsutils dnsutils && \
    rm -rf /var/lib/apt/lists/*

# Make directories for Samba
RUN mkdir -p /var/lib/samba /var/log/samba /etc/samba

# Copy entrypoint script
COPY docker/samba-test-docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# Expose ports needed by AD DC
EXPOSE 53 53/udp \
       88 88/udp \
       135 \
       139 445 \
       464 464/udp \
       389 636 \
       3268 3269

# Use volumes for persistence
#VOLUME ["/var/lib/samba", "/etc/samba", "/var/log/samba"]
RUN ls -la /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["samba-ad-dc"]

