# docker/Dockerfile.server
FROM python:3.10-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app
COPY cloudshield/ThreatDetection/requirements.txt cloudshield/ThreatDetection/requirements.txt
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r cloudshield/ThreatDetection/requirements.txt

COPY cloudshield/__init__.py cloudshield/__init__.py
COPY cloudshield/ThreatDetection cloudshield/ThreatDetection

EXPOSE 50051

CMD ["python3", "cloudshield/ThreatDetection/server.py"]
