ARG BASEOS_DIGEST
FROM docker.io/library/ubuntu:24.04${BASEOS_DIGEST:-}

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    software-properties-common \
    rsyslog systemd systemd-cron sudo wget \
    samba-ad-dc samba-ad-provision \
    krb5-user bind9-dnsutils dnsutils openssh-server net-tools vim \
    libldb-dev samba-libs ldb-tools libldb2 iputils-ping \
    iproute2 \
    acl attr winbind libpam-winbind libnss-winbind python3-setproctitle \
    libgrpc++1.51t64 libgrpc29t64 \
    build-essential cmake pkg-config libgrpc++-dev protobuf-compiler-grpc libprotobuf-dev \
    && rm -Rf /var/lib/apt/lists/* \
    && rm -Rf /usr/share/doc && rm -Rf /usr/share/man \
    && apt-get clean
RUN sed -i 's/^\($ModLoad imklog\)/#\1/' /etc/rsyslog.conf

# https://bugzilla.redhat.com/show_bug.cgi?id=1046469#c11
# https://github.com/ansible-community/molecule/issues/1104
RUN rm -f /lib/systemd/system/systemd*udev* \
    && rm -f /lib/systemd/system/getty.target
# Setup for ssh daemon
RUN mkdir /var/run/sshd \
    && sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config \
    && sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config

RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
RUN echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config
RUN echo "AuthorizedKeysFile .ssh/authorized_keys" >> /etc/ssh/sshd_config

# Make directories for Samba
RUN mkdir -p /var/lib/samba /var/log/samba /etc/samba
RUN mkdir -p /srv/samba/shares/

# Copy entrypoint script
COPY docker/samba-test-docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh

RUN chmod +x /usr/local/bin/docker-entrypoint.sh \
    && sed -i 's/\r$//' /usr/local/bin/docker-entrypoint.sh

# we created a fake sudo script for comaptibilty between docker and cloud dev/testing
RUN echo '#!/bin/sh' > /usr/local/bin/sudo && \
    echo 'exec "$@"' >> /usr/local/bin/sudo

RUN chmod +x /usr/local/bin/sudo

# build rpc server against container libs and install service
COPY cloudshield/RPCNode /tmp/RPCNode
COPY docker/cs_samba_rpc.service /etc/systemd/system/cs_rpc.service
RUN cd /tmp/RPCNode && bash scripts/proto-gen.sh \
    && cmake -S /tmp/RPCNode -B /tmp/RPCNode/build-docker \
    && cmake --build /tmp/RPCNode/build-docker --target cs-rpcsrv -j"$(nproc)" \
    && install -m 0755 /tmp/RPCNode/build-docker/cs-rpcsrv /usr/local/bin/cs-rpcsrv \
    && rm -rf /tmp/RPCNode

# Mask default Samba services at build time (AD DC uses its own service)
RUN systemctl mask smbd nmbd winbind 2>/dev/null || true

# Expose ports needed by AD DC
#EXPOSE 53 53/udp \
#       88 88/udp \
#       135 \
#       139 445 \
#       464 464/udp \
#       389 636 \
#       3268 3269

# Use volumes for persistence
#VOLUME ["/var/lib/samba", "/etc/samba", "/var/log/samba"]
#ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
#CMD ["samba-ad-dc"]

STOPSIGNAL SIGRTMIN+3

VOLUME ["/sys/fs/cgroup"]
#ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["/sbin/init"]


