FROM python:3.11-slim

RUN apt-get update && apt-get install -y curl gnupg && \
    curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(. /etc/os-release && echo $VERSION_CODENAME) main" > /etc/apt/sources.list.d/hashicorp.list && \
    apt-get update && apt-get install -y terraform bash procps net-tools && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY cloudshield/Server/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install awscli supervisor
RUN env

# If any are missing, build will fail
#RUN test -n "$AWS_ACCESS_KEY_ID" || (echo "AWS_ACCESS_KEY_ID not set" && exit 1)
#RUN test -n "$AWS_SECRET_ACCESS_KEY" || (echo "AWS_SECRET_ACCESS_KEY not set" && exit 1)
#RUN test -n "$AWS_DEFAULT_REGION" || (echo "AWS_DEFAULT_REGION not set" && exit 1)

RUN mkdir /var/lib/cloudshield

# Create logs directory for job logging
RUN mkdir -p /app/logs/jobs && chmod -R 755 /app/logs

COPY docker/supervisord.conf .
COPY cloudshield/Cloud/provisioner /app/provisioner
COPY cloudshield/Cloud/templates /var/lib/cloudshield/templates
COPY cloudshield/Server .

# drop root not needed for dev
#RUN useradd --create-home --shell /usr/sbin/nologin appuser \
#  && chown -R appuser:appuser /app
#USER appuser

CMD ["supervisord", "-c", "supervisord.conf"]
