[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0 

[program:workstations_worker]
directory=/app/cloudshield/Server
command=rq worker workstations --url redis://redis:6379
numprocs=8
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:api_worker]
directory=/app/cloudshield/Server
command=rq worker api --url redis://redis:6379
numprocs=8
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:server]
command=python /app/cloudshield/Server/server.py
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
