[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0 

[program:workstations_worker]
directory=/app
command=python cloudshield/Server/workstations_worker.py
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:api_worker]
directory=/app
command=python cloudshield/Server/api_worker.py
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:server]
command=python /app/cloudshield/Server/server.py
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
