export const managementToolbarStyles = {
  pageContent: {
    padding: 0,
    color: "var(--text-primary)",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    height: "100%",
    minHeight: 0,
    overflow: "hidden",
  },
  contentSurface: {
    flex: "1 1 auto",
    minHeight: 0,
    overflow: "hidden",
  },
  toolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    flexWrap: "wrap",
    flexShrink: 0,
  },
  leftActions: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    flex: "1 1 auto",
    flexWrap: "wrap",
    minWidth: "0",
  },
  rightActions: {
    display: "flex",
    flex: "0 0 auto",
    gap: "10px",
    flexWrap: "wrap",
    alignItems: "center",
  },
  searchField: {
    flex: "0 1 420px",
    minWidth: "220px",
    maxWidth: "420px",
    width: "auto",
  },
  selectionSummary: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  selectionSummaryCount: {
    fontSize: "12px",
    color: "var(--text-primary)",
    opacity: 0.75,
    whiteSpace: "nowrap",
  },
  clearSelectionButton: {
    border: "1px solid var(--border)",
    background: "var(--lightOverlaySubtle)",
    color: "var(--text-primary)",
    fontSize: "0.85rem",
    fontWeight: 500,
    fontFamily: "inherit",
    lineHeight: 1,
    borderRadius: "8px",
    padding: "7px 10px",
    cursor: "pointer",
    transition: "background-color 0.2s ease",
  },
  clearSelectionButtonIdleBackground: "rgba(255, 255, 255, 0.03)",
  clearSelectionButtonHoverBackground: "rgba(255, 255, 255, 0.08)",
};
