// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: infra_service/vpn_service.proto

#include "infra_service/vpn_service.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace vpn_service {
namespace v1 {
PROTOBUF_CONSTEXPR CreateVPNClientData::CreateVPNClientData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.client_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CreateVPNClientDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CreateVPNClientDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CreateVPNClientDataDefaultTypeInternal() {}
  union {
    CreateVPNClientData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CreateVPNClientDataDefaultTypeInternal _CreateVPNClientData_default_instance_;
PROTOBUF_CONSTEXPR CreateVPNClientDataAck::CreateVPNClientDataAck(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.filename_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.content_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.status_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CreateVPNClientDataAckDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CreateVPNClientDataAckDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CreateVPNClientDataAckDefaultTypeInternal() {}
  union {
    CreateVPNClientDataAck _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CreateVPNClientDataAckDefaultTypeInternal _CreateVPNClientDataAck_default_instance_;
PROTOBUF_CONSTEXPR OpenSSHTunnelData::OpenSSHTunnelData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.ipv4_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.port_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.key_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct OpenSSHTunnelDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OpenSSHTunnelDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~OpenSSHTunnelDataDefaultTypeInternal() {}
  union {
    OpenSSHTunnelData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OpenSSHTunnelDataDefaultTypeInternal _OpenSSHTunnelData_default_instance_;
PROTOBUF_CONSTEXPR OpenSSHTunnelDataAck::OpenSSHTunnelDataAck(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.port_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.status_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct OpenSSHTunnelDataAckDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OpenSSHTunnelDataAckDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~OpenSSHTunnelDataAckDefaultTypeInternal() {}
  union {
    OpenSSHTunnelDataAck _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OpenSSHTunnelDataAckDefaultTypeInternal _OpenSSHTunnelDataAck_default_instance_;
PROTOBUF_CONSTEXPR RelayData::RelayData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.ipv4_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.port_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.method_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RelayDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RelayDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RelayDataDefaultTypeInternal() {}
  union {
    RelayData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RelayDataDefaultTypeInternal _RelayData_default_instance_;
PROTOBUF_CONSTEXPR RelayDataAck::RelayDataAck(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.response_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.status_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RelayDataAckDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RelayDataAckDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RelayDataAckDefaultTypeInternal() {}
  union {
    RelayDataAck _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RelayDataAckDefaultTypeInternal _RelayDataAck_default_instance_;
}  // namespace v1
}  // namespace vpn_service
static ::_pb::Metadata file_level_metadata_infra_5fservice_2fvpn_5fservice_2eproto[6];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_infra_5fservice_2fvpn_5fservice_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_infra_5fservice_2fvpn_5fservice_2eproto = nullptr;

const uint32_t TableStruct_infra_5fservice_2fvpn_5fservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::vpn_service::v1::CreateVPNClientData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::vpn_service::v1::CreateVPNClientData, _impl_.client_name_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::vpn_service::v1::CreateVPNClientDataAck, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::vpn_service::v1::CreateVPNClientDataAck, _impl_.status_),
  PROTOBUF_FIELD_OFFSET(::vpn_service::v1::CreateVPNClientDataAck, _impl_.filename_),
  PROTOBUF_FIELD_OFFSET(::vpn_service::v1::CreateVPNClientDataAck, _impl_.content_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::vpn_service::v1::OpenSSHTunnelData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::vpn_service::v1::OpenSSHTunnelData, _impl_.ipv4_),
  PROTOBUF_FIELD_OFFSET(::vpn_service::v1::OpenSSHTunnelData, _impl_.port_),
  PROTOBUF_FIELD_OFFSET(::vpn_service::v1::OpenSSHTunnelData, _impl_.key_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::vpn_service::v1::OpenSSHTunnelDataAck, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::vpn_service::v1::OpenSSHTunnelDataAck, _impl_.status_),
  PROTOBUF_FIELD_OFFSET(::vpn_service::v1::OpenSSHTunnelDataAck, _impl_.port_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::vpn_service::v1::RelayData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::vpn_service::v1::RelayData, _impl_.ipv4_),
  PROTOBUF_FIELD_OFFSET(::vpn_service::v1::RelayData, _impl_.port_),
  PROTOBUF_FIELD_OFFSET(::vpn_service::v1::RelayData, _impl_.method_name_),
  PROTOBUF_FIELD_OFFSET(::vpn_service::v1::RelayData, _impl_.data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::vpn_service::v1::RelayDataAck, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::vpn_service::v1::RelayDataAck, _impl_.status_),
  PROTOBUF_FIELD_OFFSET(::vpn_service::v1::RelayDataAck, _impl_.response_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::vpn_service::v1::CreateVPNClientData)},
  { 7, -1, -1, sizeof(::vpn_service::v1::CreateVPNClientDataAck)},
  { 16, -1, -1, sizeof(::vpn_service::v1::OpenSSHTunnelData)},
  { 25, -1, -1, sizeof(::vpn_service::v1::OpenSSHTunnelDataAck)},
  { 33, -1, -1, sizeof(::vpn_service::v1::RelayData)},
  { 43, -1, -1, sizeof(::vpn_service::v1::RelayDataAck)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::vpn_service::v1::_CreateVPNClientData_default_instance_._instance,
  &::vpn_service::v1::_CreateVPNClientDataAck_default_instance_._instance,
  &::vpn_service::v1::_OpenSSHTunnelData_default_instance_._instance,
  &::vpn_service::v1::_OpenSSHTunnelDataAck_default_instance_._instance,
  &::vpn_service::v1::_RelayData_default_instance_._instance,
  &::vpn_service::v1::_RelayDataAck_default_instance_._instance,
};

const char descriptor_table_protodef_infra_5fservice_2fvpn_5fservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\037infra_service/vpn_service.proto\022\016vpn_s"
  "ervice.v1\"*\n\023CreateVPNClientData\022\023\n\013clie"
  "nt_name\030\001 \001(\t\"c\n\026CreateVPNClientDataAck\022"
  "&\n\006status\030\001 \001(\0162\026.vpn_service.v1.Status\022"
  "\020\n\010filename\030\002 \001(\t\022\017\n\007content\030\003 \001(\014\"<\n\021Op"
  "enSSHTunnelData\022\014\n\004ipv4\030\001 \001(\t\022\014\n\004port\030\002 "
  "\001(\t\022\013\n\003key\030\003 \001(\t\"L\n\024OpenSSHTunnelDataAck"
  "\022&\n\006status\030\001 \001(\0162\026.vpn_service.v1.Status"
  "\022\014\n\004port\030\002 \001(\t\"J\n\tRelayData\022\014\n\004ipv4\030\001 \001("
  "\t\022\014\n\004port\030\002 \001(\t\022\023\n\013method_name\030\003 \001(\t\022\014\n\004"
  "data\030\004 \001(\014\"H\n\014RelayDataAck\022&\n\006status\030\001 \001"
  "(\0162\026.vpn_service.v1.Status\022\020\n\010response\030\002"
  " \001(\014*I\n\006Status\022\013\n\007SUCCESS\020\000\022\n\n\006FAILED\020\001\022"
  "\026\n\022CONNECTION_TIMEOUT\020\002\022\016\n\nSSH_FAILED\020\0032"
  "\210\002\n\nVPNService\022^\n\017CreateVPNClient\022#.vpn_"
  "service.v1.CreateVPNClientData\032&.vpn_ser"
  "vice.v1.CreateVPNClientDataAck\022X\n\rOpenSS"
  "HTunnel\022!.vpn_service.v1.OpenSSHTunnelDa"
  "ta\032$.vpn_service.v1.OpenSSHTunnelDataAck"
  "\022@\n\005Relay\022\031.vpn_service.v1.RelayData\032\034.v"
  "pn_service.v1.RelayDataAckb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto = {
    false, false, 834, descriptor_table_protodef_infra_5fservice_2fvpn_5fservice_2eproto,
    "infra_service/vpn_service.proto",
    &descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto_once, nullptr, 0, 6,
    schemas, file_default_instances, TableStruct_infra_5fservice_2fvpn_5fservice_2eproto::offsets,
    file_level_metadata_infra_5fservice_2fvpn_5fservice_2eproto, file_level_enum_descriptors_infra_5fservice_2fvpn_5fservice_2eproto,
    file_level_service_descriptors_infra_5fservice_2fvpn_5fservice_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto_getter() {
  return &descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_infra_5fservice_2fvpn_5fservice_2eproto(&descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto);
namespace vpn_service {
namespace v1 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Status_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto);
  return file_level_enum_descriptors_infra_5fservice_2fvpn_5fservice_2eproto[0];
}
bool Status_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class CreateVPNClientData::_Internal {
 public:
};

CreateVPNClientData::CreateVPNClientData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:vpn_service.v1.CreateVPNClientData)
}
CreateVPNClientData::CreateVPNClientData(const CreateVPNClientData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CreateVPNClientData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.client_name_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.client_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.client_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_client_name().empty()) {
    _this->_impl_.client_name_.Set(from._internal_client_name(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:vpn_service.v1.CreateVPNClientData)
}

inline void CreateVPNClientData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.client_name_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.client_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.client_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

CreateVPNClientData::~CreateVPNClientData() {
  // @@protoc_insertion_point(destructor:vpn_service.v1.CreateVPNClientData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CreateVPNClientData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.client_name_.Destroy();
}

void CreateVPNClientData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CreateVPNClientData::Clear() {
// @@protoc_insertion_point(message_clear_start:vpn_service.v1.CreateVPNClientData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.client_name_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CreateVPNClientData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string client_name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_client_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "vpn_service.v1.CreateVPNClientData.client_name"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CreateVPNClientData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:vpn_service.v1.CreateVPNClientData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string client_name = 1;
  if (!this->_internal_client_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_client_name().data(), static_cast<int>(this->_internal_client_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "vpn_service.v1.CreateVPNClientData.client_name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_client_name(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:vpn_service.v1.CreateVPNClientData)
  return target;
}

size_t CreateVPNClientData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:vpn_service.v1.CreateVPNClientData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string client_name = 1;
  if (!this->_internal_client_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_client_name());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CreateVPNClientData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CreateVPNClientData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CreateVPNClientData::GetClassData() const { return &_class_data_; }


void CreateVPNClientData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CreateVPNClientData*>(&to_msg);
  auto& from = static_cast<const CreateVPNClientData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:vpn_service.v1.CreateVPNClientData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_client_name().empty()) {
    _this->_internal_set_client_name(from._internal_client_name());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CreateVPNClientData::CopyFrom(const CreateVPNClientData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:vpn_service.v1.CreateVPNClientData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CreateVPNClientData::IsInitialized() const {
  return true;
}

void CreateVPNClientData::InternalSwap(CreateVPNClientData* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.client_name_, lhs_arena,
      &other->_impl_.client_name_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata CreateVPNClientData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto_getter, &descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto_once,
      file_level_metadata_infra_5fservice_2fvpn_5fservice_2eproto[0]);
}

// ===================================================================

class CreateVPNClientDataAck::_Internal {
 public:
};

CreateVPNClientDataAck::CreateVPNClientDataAck(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:vpn_service.v1.CreateVPNClientDataAck)
}
CreateVPNClientDataAck::CreateVPNClientDataAck(const CreateVPNClientDataAck& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CreateVPNClientDataAck* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.filename_){}
    , decltype(_impl_.content_){}
    , decltype(_impl_.status_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.filename_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.filename_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_filename().empty()) {
    _this->_impl_.filename_.Set(from._internal_filename(), 
      _this->GetArenaForAllocation());
  }
  _impl_.content_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.content_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_content().empty()) {
    _this->_impl_.content_.Set(from._internal_content(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.status_ = from._impl_.status_;
  // @@protoc_insertion_point(copy_constructor:vpn_service.v1.CreateVPNClientDataAck)
}

inline void CreateVPNClientDataAck::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.filename_){}
    , decltype(_impl_.content_){}
    , decltype(_impl_.status_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.filename_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.filename_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.content_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.content_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

CreateVPNClientDataAck::~CreateVPNClientDataAck() {
  // @@protoc_insertion_point(destructor:vpn_service.v1.CreateVPNClientDataAck)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CreateVPNClientDataAck::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.filename_.Destroy();
  _impl_.content_.Destroy();
}

void CreateVPNClientDataAck::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CreateVPNClientDataAck::Clear() {
// @@protoc_insertion_point(message_clear_start:vpn_service.v1.CreateVPNClientDataAck)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.filename_.ClearToEmpty();
  _impl_.content_.ClearToEmpty();
  _impl_.status_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CreateVPNClientDataAck::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .vpn_service.v1.Status status = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_status(static_cast<::vpn_service::v1::Status>(val));
        } else
          goto handle_unusual;
        continue;
      // string filename = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_filename();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "vpn_service.v1.CreateVPNClientDataAck.filename"));
        } else
          goto handle_unusual;
        continue;
      // bytes content = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_content();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CreateVPNClientDataAck::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:vpn_service.v1.CreateVPNClientDataAck)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .vpn_service.v1.Status status = 1;
  if (this->_internal_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_status(), target);
  }

  // string filename = 2;
  if (!this->_internal_filename().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_filename().data(), static_cast<int>(this->_internal_filename().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "vpn_service.v1.CreateVPNClientDataAck.filename");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_filename(), target);
  }

  // bytes content = 3;
  if (!this->_internal_content().empty()) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_content(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:vpn_service.v1.CreateVPNClientDataAck)
  return target;
}

size_t CreateVPNClientDataAck::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:vpn_service.v1.CreateVPNClientDataAck)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string filename = 2;
  if (!this->_internal_filename().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_filename());
  }

  // bytes content = 3;
  if (!this->_internal_content().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_content());
  }

  // .vpn_service.v1.Status status = 1;
  if (this->_internal_status() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_status());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CreateVPNClientDataAck::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CreateVPNClientDataAck::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CreateVPNClientDataAck::GetClassData() const { return &_class_data_; }


void CreateVPNClientDataAck::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CreateVPNClientDataAck*>(&to_msg);
  auto& from = static_cast<const CreateVPNClientDataAck&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:vpn_service.v1.CreateVPNClientDataAck)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_filename().empty()) {
    _this->_internal_set_filename(from._internal_filename());
  }
  if (!from._internal_content().empty()) {
    _this->_internal_set_content(from._internal_content());
  }
  if (from._internal_status() != 0) {
    _this->_internal_set_status(from._internal_status());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CreateVPNClientDataAck::CopyFrom(const CreateVPNClientDataAck& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:vpn_service.v1.CreateVPNClientDataAck)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CreateVPNClientDataAck::IsInitialized() const {
  return true;
}

void CreateVPNClientDataAck::InternalSwap(CreateVPNClientDataAck* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.filename_, lhs_arena,
      &other->_impl_.filename_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.content_, lhs_arena,
      &other->_impl_.content_, rhs_arena
  );
  swap(_impl_.status_, other->_impl_.status_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CreateVPNClientDataAck::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto_getter, &descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto_once,
      file_level_metadata_infra_5fservice_2fvpn_5fservice_2eproto[1]);
}

// ===================================================================

class OpenSSHTunnelData::_Internal {
 public:
};

OpenSSHTunnelData::OpenSSHTunnelData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:vpn_service.v1.OpenSSHTunnelData)
}
OpenSSHTunnelData::OpenSSHTunnelData(const OpenSSHTunnelData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  OpenSSHTunnelData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.ipv4_){}
    , decltype(_impl_.port_){}
    , decltype(_impl_.key_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.ipv4_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ipv4_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_ipv4().empty()) {
    _this->_impl_.ipv4_.Set(from._internal_ipv4(), 
      _this->GetArenaForAllocation());
  }
  _impl_.port_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.port_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_port().empty()) {
    _this->_impl_.port_.Set(from._internal_port(), 
      _this->GetArenaForAllocation());
  }
  _impl_.key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_key().empty()) {
    _this->_impl_.key_.Set(from._internal_key(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:vpn_service.v1.OpenSSHTunnelData)
}

inline void OpenSSHTunnelData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.ipv4_){}
    , decltype(_impl_.port_){}
    , decltype(_impl_.key_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.ipv4_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ipv4_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.port_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.port_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

OpenSSHTunnelData::~OpenSSHTunnelData() {
  // @@protoc_insertion_point(destructor:vpn_service.v1.OpenSSHTunnelData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void OpenSSHTunnelData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.ipv4_.Destroy();
  _impl_.port_.Destroy();
  _impl_.key_.Destroy();
}

void OpenSSHTunnelData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void OpenSSHTunnelData::Clear() {
// @@protoc_insertion_point(message_clear_start:vpn_service.v1.OpenSSHTunnelData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ipv4_.ClearToEmpty();
  _impl_.port_.ClearToEmpty();
  _impl_.key_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* OpenSSHTunnelData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string ipv4 = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_ipv4();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "vpn_service.v1.OpenSSHTunnelData.ipv4"));
        } else
          goto handle_unusual;
        continue;
      // string port = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_port();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "vpn_service.v1.OpenSSHTunnelData.port"));
        } else
          goto handle_unusual;
        continue;
      // string key = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_key();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "vpn_service.v1.OpenSSHTunnelData.key"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* OpenSSHTunnelData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:vpn_service.v1.OpenSSHTunnelData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string ipv4 = 1;
  if (!this->_internal_ipv4().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_ipv4().data(), static_cast<int>(this->_internal_ipv4().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "vpn_service.v1.OpenSSHTunnelData.ipv4");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_ipv4(), target);
  }

  // string port = 2;
  if (!this->_internal_port().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_port().data(), static_cast<int>(this->_internal_port().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "vpn_service.v1.OpenSSHTunnelData.port");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_port(), target);
  }

  // string key = 3;
  if (!this->_internal_key().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_key().data(), static_cast<int>(this->_internal_key().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "vpn_service.v1.OpenSSHTunnelData.key");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_key(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:vpn_service.v1.OpenSSHTunnelData)
  return target;
}

size_t OpenSSHTunnelData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:vpn_service.v1.OpenSSHTunnelData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string ipv4 = 1;
  if (!this->_internal_ipv4().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_ipv4());
  }

  // string port = 2;
  if (!this->_internal_port().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_port());
  }

  // string key = 3;
  if (!this->_internal_key().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_key());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData OpenSSHTunnelData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    OpenSSHTunnelData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*OpenSSHTunnelData::GetClassData() const { return &_class_data_; }


void OpenSSHTunnelData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<OpenSSHTunnelData*>(&to_msg);
  auto& from = static_cast<const OpenSSHTunnelData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:vpn_service.v1.OpenSSHTunnelData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_ipv4().empty()) {
    _this->_internal_set_ipv4(from._internal_ipv4());
  }
  if (!from._internal_port().empty()) {
    _this->_internal_set_port(from._internal_port());
  }
  if (!from._internal_key().empty()) {
    _this->_internal_set_key(from._internal_key());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void OpenSSHTunnelData::CopyFrom(const OpenSSHTunnelData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:vpn_service.v1.OpenSSHTunnelData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OpenSSHTunnelData::IsInitialized() const {
  return true;
}

void OpenSSHTunnelData::InternalSwap(OpenSSHTunnelData* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.ipv4_, lhs_arena,
      &other->_impl_.ipv4_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.port_, lhs_arena,
      &other->_impl_.port_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.key_, lhs_arena,
      &other->_impl_.key_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata OpenSSHTunnelData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto_getter, &descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto_once,
      file_level_metadata_infra_5fservice_2fvpn_5fservice_2eproto[2]);
}

// ===================================================================

class OpenSSHTunnelDataAck::_Internal {
 public:
};

OpenSSHTunnelDataAck::OpenSSHTunnelDataAck(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:vpn_service.v1.OpenSSHTunnelDataAck)
}
OpenSSHTunnelDataAck::OpenSSHTunnelDataAck(const OpenSSHTunnelDataAck& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  OpenSSHTunnelDataAck* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.port_){}
    , decltype(_impl_.status_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.port_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.port_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_port().empty()) {
    _this->_impl_.port_.Set(from._internal_port(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.status_ = from._impl_.status_;
  // @@protoc_insertion_point(copy_constructor:vpn_service.v1.OpenSSHTunnelDataAck)
}

inline void OpenSSHTunnelDataAck::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.port_){}
    , decltype(_impl_.status_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.port_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.port_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

OpenSSHTunnelDataAck::~OpenSSHTunnelDataAck() {
  // @@protoc_insertion_point(destructor:vpn_service.v1.OpenSSHTunnelDataAck)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void OpenSSHTunnelDataAck::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.port_.Destroy();
}

void OpenSSHTunnelDataAck::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void OpenSSHTunnelDataAck::Clear() {
// @@protoc_insertion_point(message_clear_start:vpn_service.v1.OpenSSHTunnelDataAck)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.port_.ClearToEmpty();
  _impl_.status_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* OpenSSHTunnelDataAck::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .vpn_service.v1.Status status = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_status(static_cast<::vpn_service::v1::Status>(val));
        } else
          goto handle_unusual;
        continue;
      // string port = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_port();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "vpn_service.v1.OpenSSHTunnelDataAck.port"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* OpenSSHTunnelDataAck::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:vpn_service.v1.OpenSSHTunnelDataAck)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .vpn_service.v1.Status status = 1;
  if (this->_internal_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_status(), target);
  }

  // string port = 2;
  if (!this->_internal_port().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_port().data(), static_cast<int>(this->_internal_port().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "vpn_service.v1.OpenSSHTunnelDataAck.port");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_port(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:vpn_service.v1.OpenSSHTunnelDataAck)
  return target;
}

size_t OpenSSHTunnelDataAck::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:vpn_service.v1.OpenSSHTunnelDataAck)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string port = 2;
  if (!this->_internal_port().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_port());
  }

  // .vpn_service.v1.Status status = 1;
  if (this->_internal_status() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_status());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData OpenSSHTunnelDataAck::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    OpenSSHTunnelDataAck::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*OpenSSHTunnelDataAck::GetClassData() const { return &_class_data_; }


void OpenSSHTunnelDataAck::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<OpenSSHTunnelDataAck*>(&to_msg);
  auto& from = static_cast<const OpenSSHTunnelDataAck&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:vpn_service.v1.OpenSSHTunnelDataAck)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_port().empty()) {
    _this->_internal_set_port(from._internal_port());
  }
  if (from._internal_status() != 0) {
    _this->_internal_set_status(from._internal_status());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void OpenSSHTunnelDataAck::CopyFrom(const OpenSSHTunnelDataAck& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:vpn_service.v1.OpenSSHTunnelDataAck)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OpenSSHTunnelDataAck::IsInitialized() const {
  return true;
}

void OpenSSHTunnelDataAck::InternalSwap(OpenSSHTunnelDataAck* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.port_, lhs_arena,
      &other->_impl_.port_, rhs_arena
  );
  swap(_impl_.status_, other->_impl_.status_);
}

::PROTOBUF_NAMESPACE_ID::Metadata OpenSSHTunnelDataAck::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto_getter, &descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto_once,
      file_level_metadata_infra_5fservice_2fvpn_5fservice_2eproto[3]);
}

// ===================================================================

class RelayData::_Internal {
 public:
};

RelayData::RelayData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:vpn_service.v1.RelayData)
}
RelayData::RelayData(const RelayData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RelayData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.ipv4_){}
    , decltype(_impl_.port_){}
    , decltype(_impl_.method_name_){}
    , decltype(_impl_.data_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.ipv4_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ipv4_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_ipv4().empty()) {
    _this->_impl_.ipv4_.Set(from._internal_ipv4(), 
      _this->GetArenaForAllocation());
  }
  _impl_.port_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.port_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_port().empty()) {
    _this->_impl_.port_.Set(from._internal_port(), 
      _this->GetArenaForAllocation());
  }
  _impl_.method_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.method_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_method_name().empty()) {
    _this->_impl_.method_name_.Set(from._internal_method_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_data().empty()) {
    _this->_impl_.data_.Set(from._internal_data(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:vpn_service.v1.RelayData)
}

inline void RelayData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.ipv4_){}
    , decltype(_impl_.port_){}
    , decltype(_impl_.method_name_){}
    , decltype(_impl_.data_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.ipv4_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ipv4_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.port_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.port_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.method_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.method_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

RelayData::~RelayData() {
  // @@protoc_insertion_point(destructor:vpn_service.v1.RelayData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RelayData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.ipv4_.Destroy();
  _impl_.port_.Destroy();
  _impl_.method_name_.Destroy();
  _impl_.data_.Destroy();
}

void RelayData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RelayData::Clear() {
// @@protoc_insertion_point(message_clear_start:vpn_service.v1.RelayData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ipv4_.ClearToEmpty();
  _impl_.port_.ClearToEmpty();
  _impl_.method_name_.ClearToEmpty();
  _impl_.data_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RelayData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string ipv4 = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_ipv4();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "vpn_service.v1.RelayData.ipv4"));
        } else
          goto handle_unusual;
        continue;
      // string port = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_port();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "vpn_service.v1.RelayData.port"));
        } else
          goto handle_unusual;
        continue;
      // string method_name = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_method_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "vpn_service.v1.RelayData.method_name"));
        } else
          goto handle_unusual;
        continue;
      // bytes data = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RelayData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:vpn_service.v1.RelayData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string ipv4 = 1;
  if (!this->_internal_ipv4().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_ipv4().data(), static_cast<int>(this->_internal_ipv4().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "vpn_service.v1.RelayData.ipv4");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_ipv4(), target);
  }

  // string port = 2;
  if (!this->_internal_port().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_port().data(), static_cast<int>(this->_internal_port().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "vpn_service.v1.RelayData.port");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_port(), target);
  }

  // string method_name = 3;
  if (!this->_internal_method_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_method_name().data(), static_cast<int>(this->_internal_method_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "vpn_service.v1.RelayData.method_name");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_method_name(), target);
  }

  // bytes data = 4;
  if (!this->_internal_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        4, this->_internal_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:vpn_service.v1.RelayData)
  return target;
}

size_t RelayData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:vpn_service.v1.RelayData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string ipv4 = 1;
  if (!this->_internal_ipv4().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_ipv4());
  }

  // string port = 2;
  if (!this->_internal_port().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_port());
  }

  // string method_name = 3;
  if (!this->_internal_method_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_method_name());
  }

  // bytes data = 4;
  if (!this->_internal_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_data());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RelayData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RelayData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RelayData::GetClassData() const { return &_class_data_; }


void RelayData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RelayData*>(&to_msg);
  auto& from = static_cast<const RelayData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:vpn_service.v1.RelayData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_ipv4().empty()) {
    _this->_internal_set_ipv4(from._internal_ipv4());
  }
  if (!from._internal_port().empty()) {
    _this->_internal_set_port(from._internal_port());
  }
  if (!from._internal_method_name().empty()) {
    _this->_internal_set_method_name(from._internal_method_name());
  }
  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RelayData::CopyFrom(const RelayData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:vpn_service.v1.RelayData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RelayData::IsInitialized() const {
  return true;
}

void RelayData::InternalSwap(RelayData* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.ipv4_, lhs_arena,
      &other->_impl_.ipv4_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.port_, lhs_arena,
      &other->_impl_.port_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.method_name_, lhs_arena,
      &other->_impl_.method_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.data_, lhs_arena,
      &other->_impl_.data_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata RelayData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto_getter, &descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto_once,
      file_level_metadata_infra_5fservice_2fvpn_5fservice_2eproto[4]);
}

// ===================================================================

class RelayDataAck::_Internal {
 public:
};

RelayDataAck::RelayDataAck(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:vpn_service.v1.RelayDataAck)
}
RelayDataAck::RelayDataAck(const RelayDataAck& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RelayDataAck* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.response_){}
    , decltype(_impl_.status_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.response_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.response_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_response().empty()) {
    _this->_impl_.response_.Set(from._internal_response(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.status_ = from._impl_.status_;
  // @@protoc_insertion_point(copy_constructor:vpn_service.v1.RelayDataAck)
}

inline void RelayDataAck::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.response_){}
    , decltype(_impl_.status_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.response_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.response_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

RelayDataAck::~RelayDataAck() {
  // @@protoc_insertion_point(destructor:vpn_service.v1.RelayDataAck)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RelayDataAck::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.response_.Destroy();
}

void RelayDataAck::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RelayDataAck::Clear() {
// @@protoc_insertion_point(message_clear_start:vpn_service.v1.RelayDataAck)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.response_.ClearToEmpty();
  _impl_.status_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RelayDataAck::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .vpn_service.v1.Status status = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_status(static_cast<::vpn_service::v1::Status>(val));
        } else
          goto handle_unusual;
        continue;
      // bytes response = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_response();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RelayDataAck::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:vpn_service.v1.RelayDataAck)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .vpn_service.v1.Status status = 1;
  if (this->_internal_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_status(), target);
  }

  // bytes response = 2;
  if (!this->_internal_response().empty()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_response(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:vpn_service.v1.RelayDataAck)
  return target;
}

size_t RelayDataAck::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:vpn_service.v1.RelayDataAck)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes response = 2;
  if (!this->_internal_response().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_response());
  }

  // .vpn_service.v1.Status status = 1;
  if (this->_internal_status() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_status());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RelayDataAck::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RelayDataAck::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RelayDataAck::GetClassData() const { return &_class_data_; }


void RelayDataAck::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RelayDataAck*>(&to_msg);
  auto& from = static_cast<const RelayDataAck&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:vpn_service.v1.RelayDataAck)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_response().empty()) {
    _this->_internal_set_response(from._internal_response());
  }
  if (from._internal_status() != 0) {
    _this->_internal_set_status(from._internal_status());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RelayDataAck::CopyFrom(const RelayDataAck& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:vpn_service.v1.RelayDataAck)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RelayDataAck::IsInitialized() const {
  return true;
}

void RelayDataAck::InternalSwap(RelayDataAck* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.response_, lhs_arena,
      &other->_impl_.response_, rhs_arena
  );
  swap(_impl_.status_, other->_impl_.status_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RelayDataAck::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto_getter, &descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto_once,
      file_level_metadata_infra_5fservice_2fvpn_5fservice_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace vpn_service
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::vpn_service::v1::CreateVPNClientData*
Arena::CreateMaybeMessage< ::vpn_service::v1::CreateVPNClientData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::vpn_service::v1::CreateVPNClientData >(arena);
}
template<> PROTOBUF_NOINLINE ::vpn_service::v1::CreateVPNClientDataAck*
Arena::CreateMaybeMessage< ::vpn_service::v1::CreateVPNClientDataAck >(Arena* arena) {
  return Arena::CreateMessageInternal< ::vpn_service::v1::CreateVPNClientDataAck >(arena);
}
template<> PROTOBUF_NOINLINE ::vpn_service::v1::OpenSSHTunnelData*
Arena::CreateMaybeMessage< ::vpn_service::v1::OpenSSHTunnelData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::vpn_service::v1::OpenSSHTunnelData >(arena);
}
template<> PROTOBUF_NOINLINE ::vpn_service::v1::OpenSSHTunnelDataAck*
Arena::CreateMaybeMessage< ::vpn_service::v1::OpenSSHTunnelDataAck >(Arena* arena) {
  return Arena::CreateMessageInternal< ::vpn_service::v1::OpenSSHTunnelDataAck >(arena);
}
template<> PROTOBUF_NOINLINE ::vpn_service::v1::RelayData*
Arena::CreateMaybeMessage< ::vpn_service::v1::RelayData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::vpn_service::v1::RelayData >(arena);
}
template<> PROTOBUF_NOINLINE ::vpn_service::v1::RelayDataAck*
Arena::CreateMaybeMessage< ::vpn_service::v1::RelayDataAck >(Arena* arena) {
  return Arena::CreateMessageInternal< ::vpn_service::v1::RelayDataAck >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
