// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: infra_service/vpn_service.proto
// Protobuf C++ Version: 6.31.1

#include "infra_service/vpn_service.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace vpn_service {
namespace v1 {

inline constexpr RelayDataAck::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        response_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        status_{static_cast< ::vpn_service::v1::Status >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR RelayDataAck::RelayDataAck(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RelayDataAck_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RelayDataAckDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RelayDataAckDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RelayDataAckDefaultTypeInternal() {}
  union {
    RelayDataAck _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RelayDataAckDefaultTypeInternal _RelayDataAck_default_instance_;

inline constexpr RelayData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        ipv4_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        port_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        method_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR RelayData::RelayData(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RelayData_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RelayDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RelayDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RelayDataDefaultTypeInternal() {}
  union {
    RelayData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RelayDataDefaultTypeInternal _RelayData_default_instance_;

inline constexpr OpenSSHTunnelDataAck::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        port_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        status_{static_cast< ::vpn_service::v1::Status >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR OpenSSHTunnelDataAck::OpenSSHTunnelDataAck(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(OpenSSHTunnelDataAck_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct OpenSSHTunnelDataAckDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OpenSSHTunnelDataAckDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OpenSSHTunnelDataAckDefaultTypeInternal() {}
  union {
    OpenSSHTunnelDataAck _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OpenSSHTunnelDataAckDefaultTypeInternal _OpenSSHTunnelDataAck_default_instance_;

inline constexpr OpenSSHTunnelData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        ipv4_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        port_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        key_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR OpenSSHTunnelData::OpenSSHTunnelData(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(OpenSSHTunnelData_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct OpenSSHTunnelDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OpenSSHTunnelDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OpenSSHTunnelDataDefaultTypeInternal() {}
  union {
    OpenSSHTunnelData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OpenSSHTunnelDataDefaultTypeInternal _OpenSSHTunnelData_default_instance_;

inline constexpr CreateVPNClientDataAck::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        filename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        content_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        status_{static_cast< ::vpn_service::v1::Status >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR CreateVPNClientDataAck::CreateVPNClientDataAck(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CreateVPNClientDataAck_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CreateVPNClientDataAckDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CreateVPNClientDataAckDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CreateVPNClientDataAckDefaultTypeInternal() {}
  union {
    CreateVPNClientDataAck _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CreateVPNClientDataAckDefaultTypeInternal _CreateVPNClientDataAck_default_instance_;

inline constexpr CreateVPNClientData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        client_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR CreateVPNClientData::CreateVPNClientData(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CreateVPNClientData_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CreateVPNClientDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CreateVPNClientDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CreateVPNClientDataDefaultTypeInternal() {}
  union {
    CreateVPNClientData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CreateVPNClientDataDefaultTypeInternal _CreateVPNClientData_default_instance_;
}  // namespace v1
}  // namespace vpn_service
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_infra_5fservice_2fvpn_5fservice_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_infra_5fservice_2fvpn_5fservice_2eproto = nullptr;
const ::uint32_t
    TableStruct_infra_5fservice_2fvpn_5fservice_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::vpn_service::v1::CreateVPNClientData, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::vpn_service::v1::CreateVPNClientData, _impl_.client_name_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::vpn_service::v1::CreateVPNClientDataAck, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::vpn_service::v1::CreateVPNClientDataAck, _impl_.status_),
        PROTOBUF_FIELD_OFFSET(::vpn_service::v1::CreateVPNClientDataAck, _impl_.filename_),
        PROTOBUF_FIELD_OFFSET(::vpn_service::v1::CreateVPNClientDataAck, _impl_.content_),
        2,
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::vpn_service::v1::OpenSSHTunnelData, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::vpn_service::v1::OpenSSHTunnelData, _impl_.ipv4_),
        PROTOBUF_FIELD_OFFSET(::vpn_service::v1::OpenSSHTunnelData, _impl_.port_),
        PROTOBUF_FIELD_OFFSET(::vpn_service::v1::OpenSSHTunnelData, _impl_.key_),
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::vpn_service::v1::OpenSSHTunnelDataAck, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::vpn_service::v1::OpenSSHTunnelDataAck, _impl_.status_),
        PROTOBUF_FIELD_OFFSET(::vpn_service::v1::OpenSSHTunnelDataAck, _impl_.port_),
        1,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::vpn_service::v1::RelayData, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::vpn_service::v1::RelayData, _impl_.ipv4_),
        PROTOBUF_FIELD_OFFSET(::vpn_service::v1::RelayData, _impl_.port_),
        PROTOBUF_FIELD_OFFSET(::vpn_service::v1::RelayData, _impl_.method_name_),
        PROTOBUF_FIELD_OFFSET(::vpn_service::v1::RelayData, _impl_.data_),
        0,
        1,
        2,
        3,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::vpn_service::v1::RelayDataAck, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::vpn_service::v1::RelayDataAck, _impl_.status_),
        PROTOBUF_FIELD_OFFSET(::vpn_service::v1::RelayDataAck, _impl_.response_),
        1,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::vpn_service::v1::CreateVPNClientData)},
        {5, sizeof(::vpn_service::v1::CreateVPNClientDataAck)},
        {14, sizeof(::vpn_service::v1::OpenSSHTunnelData)},
        {23, sizeof(::vpn_service::v1::OpenSSHTunnelDataAck)},
        {30, sizeof(::vpn_service::v1::RelayData)},
        {41, sizeof(::vpn_service::v1::RelayDataAck)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::vpn_service::v1::_CreateVPNClientData_default_instance_._instance,
    &::vpn_service::v1::_CreateVPNClientDataAck_default_instance_._instance,
    &::vpn_service::v1::_OpenSSHTunnelData_default_instance_._instance,
    &::vpn_service::v1::_OpenSSHTunnelDataAck_default_instance_._instance,
    &::vpn_service::v1::_RelayData_default_instance_._instance,
    &::vpn_service::v1::_RelayDataAck_default_instance_._instance,
};
const char descriptor_table_protodef_infra_5fservice_2fvpn_5fservice_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\037infra_service/vpn_service.proto\022\016vpn_s"
    "ervice.v1\"*\n\023CreateVPNClientData\022\023\n\013clie"
    "nt_name\030\001 \001(\t\"c\n\026CreateVPNClientDataAck\022"
    "&\n\006status\030\001 \001(\0162\026.vpn_service.v1.Status\022"
    "\020\n\010filename\030\002 \001(\t\022\017\n\007content\030\003 \001(\014\"<\n\021Op"
    "enSSHTunnelData\022\014\n\004ipv4\030\001 \001(\t\022\014\n\004port\030\002 "
    "\001(\t\022\013\n\003key\030\003 \001(\t\"L\n\024OpenSSHTunnelDataAck"
    "\022&\n\006status\030\001 \001(\0162\026.vpn_service.v1.Status"
    "\022\014\n\004port\030\002 \001(\t\"J\n\tRelayData\022\014\n\004ipv4\030\001 \001("
    "\t\022\014\n\004port\030\002 \001(\t\022\023\n\013method_name\030\003 \001(\t\022\014\n\004"
    "data\030\004 \001(\014\"H\n\014RelayDataAck\022&\n\006status\030\001 \001"
    "(\0162\026.vpn_service.v1.Status\022\020\n\010response\030\002"
    " \001(\014*I\n\006Status\022\013\n\007SUCCESS\020\000\022\n\n\006FAILED\020\001\022"
    "\026\n\022CONNECTION_TIMEOUT\020\002\022\016\n\nSSH_FAILED\020\0032"
    "\210\002\n\nVPNService\022^\n\017CreateVPNClient\022#.vpn_"
    "service.v1.CreateVPNClientData\032&.vpn_ser"
    "vice.v1.CreateVPNClientDataAck\022X\n\rOpenSS"
    "HTunnel\022!.vpn_service.v1.OpenSSHTunnelDa"
    "ta\032$.vpn_service.v1.OpenSSHTunnelDataAck"
    "\022@\n\005Relay\022\031.vpn_service.v1.RelayData\032\034.v"
    "pn_service.v1.RelayDataAckb\006proto3"
};
static ::absl::once_flag descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto = {
    false,
    false,
    834,
    descriptor_table_protodef_infra_5fservice_2fvpn_5fservice_2eproto,
    "infra_service/vpn_service.proto",
    &descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto_once,
    nullptr,
    0,
    6,
    schemas,
    file_default_instances,
    TableStruct_infra_5fservice_2fvpn_5fservice_2eproto::offsets,
    file_level_enum_descriptors_infra_5fservice_2fvpn_5fservice_2eproto,
    file_level_service_descriptors_infra_5fservice_2fvpn_5fservice_2eproto,
};
namespace vpn_service {
namespace v1 {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Status_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto);
  return file_level_enum_descriptors_infra_5fservice_2fvpn_5fservice_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Status_internal_data_[] = {
    262144u, 0u, };
// ===================================================================

class CreateVPNClientData::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CreateVPNClientData>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CreateVPNClientData, _impl_._has_bits_);
};

CreateVPNClientData::CreateVPNClientData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CreateVPNClientData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:vpn_service.v1.CreateVPNClientData)
}
PROTOBUF_NDEBUG_INLINE CreateVPNClientData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::vpn_service::v1::CreateVPNClientData& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        client_name_(arena, from.client_name_) {}

CreateVPNClientData::CreateVPNClientData(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CreateVPNClientData& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CreateVPNClientData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CreateVPNClientData* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:vpn_service.v1.CreateVPNClientData)
}
PROTOBUF_NDEBUG_INLINE CreateVPNClientData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        client_name_(arena) {}

inline void CreateVPNClientData::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CreateVPNClientData::~CreateVPNClientData() {
  // @@protoc_insertion_point(destructor:vpn_service.v1.CreateVPNClientData)
  SharedDtor(*this);
}
inline void CreateVPNClientData::SharedDtor(MessageLite& self) {
  CreateVPNClientData& this_ = static_cast<CreateVPNClientData&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.client_name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CreateVPNClientData::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CreateVPNClientData(arena);
}
constexpr auto CreateVPNClientData::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CreateVPNClientData),
                                            alignof(CreateVPNClientData));
}
constexpr auto CreateVPNClientData::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CreateVPNClientData_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CreateVPNClientData::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CreateVPNClientData>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CreateVPNClientData::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CreateVPNClientData>(), &CreateVPNClientData::ByteSizeLong,
              &CreateVPNClientData::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CreateVPNClientData, _impl_._cached_size_),
          false,
      },
      &CreateVPNClientData::kDescriptorMethods,
      &descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CreateVPNClientData_class_data_ =
        CreateVPNClientData::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CreateVPNClientData::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CreateVPNClientData_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CreateVPNClientData_class_data_.tc_table);
  return CreateVPNClientData_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 54, 2>
CreateVPNClientData::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CreateVPNClientData, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CreateVPNClientData_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::vpn_service::v1::CreateVPNClientData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string client_name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(CreateVPNClientData, _impl_.client_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string client_name = 1;
    {PROTOBUF_FIELD_OFFSET(CreateVPNClientData, _impl_.client_name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\42\13\0\0\0\0\0\0"
    "vpn_service.v1.CreateVPNClientData"
    "client_name"
  }},
};
PROTOBUF_NOINLINE void CreateVPNClientData::Clear() {
// @@protoc_insertion_point(message_clear_start:vpn_service.v1.CreateVPNClientData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.client_name_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CreateVPNClientData::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CreateVPNClientData& this_ = static_cast<const CreateVPNClientData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CreateVPNClientData::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CreateVPNClientData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:vpn_service.v1.CreateVPNClientData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string client_name = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_client_name().empty()) {
      const ::std::string& _s = this_._internal_client_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "vpn_service.v1.CreateVPNClientData.client_name");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:vpn_service.v1.CreateVPNClientData)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CreateVPNClientData::ByteSizeLong(const MessageLite& base) {
  const CreateVPNClientData& this_ = static_cast<const CreateVPNClientData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CreateVPNClientData::ByteSizeLong() const {
  const CreateVPNClientData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:vpn_service.v1.CreateVPNClientData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string client_name = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_client_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_client_name());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CreateVPNClientData::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CreateVPNClientData*>(&to_msg);
  auto& from = static_cast<const CreateVPNClientData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:vpn_service.v1.CreateVPNClientData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (!from._internal_client_name().empty()) {
      _this->_internal_set_client_name(from._internal_client_name());
    } else {
      if (_this->_impl_.client_name_.IsDefault()) {
        _this->_internal_set_client_name("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CreateVPNClientData::CopyFrom(const CreateVPNClientData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:vpn_service.v1.CreateVPNClientData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CreateVPNClientData::InternalSwap(CreateVPNClientData* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.client_name_, &other->_impl_.client_name_, arena);
}

::google::protobuf::Metadata CreateVPNClientData::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CreateVPNClientDataAck::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CreateVPNClientDataAck>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CreateVPNClientDataAck, _impl_._has_bits_);
};

CreateVPNClientDataAck::CreateVPNClientDataAck(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CreateVPNClientDataAck_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:vpn_service.v1.CreateVPNClientDataAck)
}
PROTOBUF_NDEBUG_INLINE CreateVPNClientDataAck::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::vpn_service::v1::CreateVPNClientDataAck& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        filename_(arena, from.filename_),
        content_(arena, from.content_) {}

CreateVPNClientDataAck::CreateVPNClientDataAck(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CreateVPNClientDataAck& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CreateVPNClientDataAck_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CreateVPNClientDataAck* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.status_ = from._impl_.status_;

  // @@protoc_insertion_point(copy_constructor:vpn_service.v1.CreateVPNClientDataAck)
}
PROTOBUF_NDEBUG_INLINE CreateVPNClientDataAck::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        filename_(arena),
        content_(arena) {}

inline void CreateVPNClientDataAck::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.status_ = {};
}
CreateVPNClientDataAck::~CreateVPNClientDataAck() {
  // @@protoc_insertion_point(destructor:vpn_service.v1.CreateVPNClientDataAck)
  SharedDtor(*this);
}
inline void CreateVPNClientDataAck::SharedDtor(MessageLite& self) {
  CreateVPNClientDataAck& this_ = static_cast<CreateVPNClientDataAck&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.filename_.Destroy();
  this_._impl_.content_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CreateVPNClientDataAck::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CreateVPNClientDataAck(arena);
}
constexpr auto CreateVPNClientDataAck::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CreateVPNClientDataAck),
                                            alignof(CreateVPNClientDataAck));
}
constexpr auto CreateVPNClientDataAck::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CreateVPNClientDataAck_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CreateVPNClientDataAck::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CreateVPNClientDataAck>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CreateVPNClientDataAck::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CreateVPNClientDataAck>(), &CreateVPNClientDataAck::ByteSizeLong,
              &CreateVPNClientDataAck::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CreateVPNClientDataAck, _impl_._cached_size_),
          false,
      },
      &CreateVPNClientDataAck::kDescriptorMethods,
      &descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CreateVPNClientDataAck_class_data_ =
        CreateVPNClientDataAck::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CreateVPNClientDataAck::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CreateVPNClientDataAck_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CreateVPNClientDataAck_class_data_.tc_table);
  return CreateVPNClientDataAck_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 54, 2>
CreateVPNClientDataAck::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CreateVPNClientDataAck, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CreateVPNClientDataAck_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::vpn_service::v1::CreateVPNClientDataAck>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .vpn_service.v1.Status status = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CreateVPNClientDataAck, _impl_.status_), 2>(),
     {8, 2, 0, PROTOBUF_FIELD_OFFSET(CreateVPNClientDataAck, _impl_.status_)}},
    // string filename = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(CreateVPNClientDataAck, _impl_.filename_)}},
    // bytes content = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 1, 0, PROTOBUF_FIELD_OFFSET(CreateVPNClientDataAck, _impl_.content_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .vpn_service.v1.Status status = 1;
    {PROTOBUF_FIELD_OFFSET(CreateVPNClientDataAck, _impl_.status_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // string filename = 2;
    {PROTOBUF_FIELD_OFFSET(CreateVPNClientDataAck, _impl_.filename_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes content = 3;
    {PROTOBUF_FIELD_OFFSET(CreateVPNClientDataAck, _impl_.content_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\45\0\10\0\0\0\0\0"
    "vpn_service.v1.CreateVPNClientDataAck"
    "filename"
  }},
};
PROTOBUF_NOINLINE void CreateVPNClientDataAck::Clear() {
// @@protoc_insertion_point(message_clear_start:vpn_service.v1.CreateVPNClientDataAck)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.filename_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _impl_.content_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.status_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CreateVPNClientDataAck::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CreateVPNClientDataAck& this_ = static_cast<const CreateVPNClientDataAck&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CreateVPNClientDataAck::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CreateVPNClientDataAck& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:vpn_service.v1.CreateVPNClientDataAck)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .vpn_service.v1.Status status = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (this_._internal_status() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_status(), target);
    }
  }

  // string filename = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_filename().empty()) {
      const ::std::string& _s = this_._internal_filename();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "vpn_service.v1.CreateVPNClientDataAck.filename");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // bytes content = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (!this_._internal_content().empty()) {
      const ::std::string& _s = this_._internal_content();
      target = stream->WriteBytesMaybeAliased(3, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:vpn_service.v1.CreateVPNClientDataAck)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CreateVPNClientDataAck::ByteSizeLong(const MessageLite& base) {
  const CreateVPNClientDataAck& this_ = static_cast<const CreateVPNClientDataAck&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CreateVPNClientDataAck::ByteSizeLong() const {
  const CreateVPNClientDataAck& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:vpn_service.v1.CreateVPNClientDataAck)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    // string filename = 2;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_filename().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_filename());
      }
    }
    // bytes content = 3;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!this_._internal_content().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_content());
      }
    }
    // .vpn_service.v1.Status status = 1;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (this_._internal_status() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_status());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CreateVPNClientDataAck::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CreateVPNClientDataAck*>(&to_msg);
  auto& from = static_cast<const CreateVPNClientDataAck&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:vpn_service.v1.CreateVPNClientDataAck)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_filename().empty()) {
        _this->_internal_set_filename(from._internal_filename());
      } else {
        if (_this->_impl_.filename_.IsDefault()) {
          _this->_internal_set_filename("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!from._internal_content().empty()) {
        _this->_internal_set_content(from._internal_content());
      } else {
        if (_this->_impl_.content_.IsDefault()) {
          _this->_internal_set_content("");
        }
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (from._internal_status() != 0) {
        _this->_impl_.status_ = from._impl_.status_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CreateVPNClientDataAck::CopyFrom(const CreateVPNClientDataAck& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:vpn_service.v1.CreateVPNClientDataAck)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CreateVPNClientDataAck::InternalSwap(CreateVPNClientDataAck* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filename_, &other->_impl_.filename_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.content_, &other->_impl_.content_, arena);
  swap(_impl_.status_, other->_impl_.status_);
}

::google::protobuf::Metadata CreateVPNClientDataAck::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class OpenSSHTunnelData::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<OpenSSHTunnelData>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(OpenSSHTunnelData, _impl_._has_bits_);
};

OpenSSHTunnelData::OpenSSHTunnelData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, OpenSSHTunnelData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:vpn_service.v1.OpenSSHTunnelData)
}
PROTOBUF_NDEBUG_INLINE OpenSSHTunnelData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::vpn_service::v1::OpenSSHTunnelData& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        ipv4_(arena, from.ipv4_),
        port_(arena, from.port_),
        key_(arena, from.key_) {}

OpenSSHTunnelData::OpenSSHTunnelData(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const OpenSSHTunnelData& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, OpenSSHTunnelData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  OpenSSHTunnelData* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:vpn_service.v1.OpenSSHTunnelData)
}
PROTOBUF_NDEBUG_INLINE OpenSSHTunnelData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        ipv4_(arena),
        port_(arena),
        key_(arena) {}

inline void OpenSSHTunnelData::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
OpenSSHTunnelData::~OpenSSHTunnelData() {
  // @@protoc_insertion_point(destructor:vpn_service.v1.OpenSSHTunnelData)
  SharedDtor(*this);
}
inline void OpenSSHTunnelData::SharedDtor(MessageLite& self) {
  OpenSSHTunnelData& this_ = static_cast<OpenSSHTunnelData&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.ipv4_.Destroy();
  this_._impl_.port_.Destroy();
  this_._impl_.key_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL OpenSSHTunnelData::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) OpenSSHTunnelData(arena);
}
constexpr auto OpenSSHTunnelData::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(OpenSSHTunnelData),
                                            alignof(OpenSSHTunnelData));
}
constexpr auto OpenSSHTunnelData::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_OpenSSHTunnelData_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &OpenSSHTunnelData::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<OpenSSHTunnelData>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &OpenSSHTunnelData::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<OpenSSHTunnelData>(), &OpenSSHTunnelData::ByteSizeLong,
              &OpenSSHTunnelData::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(OpenSSHTunnelData, _impl_._cached_size_),
          false,
      },
      &OpenSSHTunnelData::kDescriptorMethods,
      &descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull OpenSSHTunnelData_class_data_ =
        OpenSSHTunnelData::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
OpenSSHTunnelData::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&OpenSSHTunnelData_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(OpenSSHTunnelData_class_data_.tc_table);
  return OpenSSHTunnelData_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 52, 2>
OpenSSHTunnelData::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(OpenSSHTunnelData, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    OpenSSHTunnelData_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::vpn_service::v1::OpenSSHTunnelData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string ipv4 = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(OpenSSHTunnelData, _impl_.ipv4_)}},
    // string port = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(OpenSSHTunnelData, _impl_.port_)}},
    // string key = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 2, 0, PROTOBUF_FIELD_OFFSET(OpenSSHTunnelData, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string ipv4 = 1;
    {PROTOBUF_FIELD_OFFSET(OpenSSHTunnelData, _impl_.ipv4_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string port = 2;
    {PROTOBUF_FIELD_OFFSET(OpenSSHTunnelData, _impl_.port_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string key = 3;
    {PROTOBUF_FIELD_OFFSET(OpenSSHTunnelData, _impl_.key_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\40\4\4\3\0\0\0\0"
    "vpn_service.v1.OpenSSHTunnelData"
    "ipv4"
    "port"
    "key"
  }},
};
PROTOBUF_NOINLINE void OpenSSHTunnelData::Clear() {
// @@protoc_insertion_point(message_clear_start:vpn_service.v1.OpenSSHTunnelData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.ipv4_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _impl_.port_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _impl_.key_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL OpenSSHTunnelData::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const OpenSSHTunnelData& this_ = static_cast<const OpenSSHTunnelData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL OpenSSHTunnelData::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const OpenSSHTunnelData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:vpn_service.v1.OpenSSHTunnelData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string ipv4 = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_ipv4().empty()) {
      const ::std::string& _s = this_._internal_ipv4();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "vpn_service.v1.OpenSSHTunnelData.ipv4");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string port = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (!this_._internal_port().empty()) {
      const ::std::string& _s = this_._internal_port();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "vpn_service.v1.OpenSSHTunnelData.port");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // string key = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (!this_._internal_key().empty()) {
      const ::std::string& _s = this_._internal_key();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "vpn_service.v1.OpenSSHTunnelData.key");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:vpn_service.v1.OpenSSHTunnelData)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t OpenSSHTunnelData::ByteSizeLong(const MessageLite& base) {
  const OpenSSHTunnelData& this_ = static_cast<const OpenSSHTunnelData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t OpenSSHTunnelData::ByteSizeLong() const {
  const OpenSSHTunnelData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:vpn_service.v1.OpenSSHTunnelData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    // string ipv4 = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_ipv4().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_ipv4());
      }
    }
    // string port = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!this_._internal_port().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_port());
      }
    }
    // string key = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (!this_._internal_key().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_key());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void OpenSSHTunnelData::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<OpenSSHTunnelData*>(&to_msg);
  auto& from = static_cast<const OpenSSHTunnelData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:vpn_service.v1.OpenSSHTunnelData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_ipv4().empty()) {
        _this->_internal_set_ipv4(from._internal_ipv4());
      } else {
        if (_this->_impl_.ipv4_.IsDefault()) {
          _this->_internal_set_ipv4("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!from._internal_port().empty()) {
        _this->_internal_set_port(from._internal_port());
      } else {
        if (_this->_impl_.port_.IsDefault()) {
          _this->_internal_set_port("");
        }
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (!from._internal_key().empty()) {
        _this->_internal_set_key(from._internal_key());
      } else {
        if (_this->_impl_.key_.IsDefault()) {
          _this->_internal_set_key("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void OpenSSHTunnelData::CopyFrom(const OpenSSHTunnelData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:vpn_service.v1.OpenSSHTunnelData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void OpenSSHTunnelData::InternalSwap(OpenSSHTunnelData* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ipv4_, &other->_impl_.ipv4_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.port_, &other->_impl_.port_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.key_, &other->_impl_.key_, arena);
}

::google::protobuf::Metadata OpenSSHTunnelData::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class OpenSSHTunnelDataAck::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<OpenSSHTunnelDataAck>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(OpenSSHTunnelDataAck, _impl_._has_bits_);
};

OpenSSHTunnelDataAck::OpenSSHTunnelDataAck(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, OpenSSHTunnelDataAck_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:vpn_service.v1.OpenSSHTunnelDataAck)
}
PROTOBUF_NDEBUG_INLINE OpenSSHTunnelDataAck::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::vpn_service::v1::OpenSSHTunnelDataAck& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        port_(arena, from.port_) {}

OpenSSHTunnelDataAck::OpenSSHTunnelDataAck(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const OpenSSHTunnelDataAck& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, OpenSSHTunnelDataAck_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  OpenSSHTunnelDataAck* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.status_ = from._impl_.status_;

  // @@protoc_insertion_point(copy_constructor:vpn_service.v1.OpenSSHTunnelDataAck)
}
PROTOBUF_NDEBUG_INLINE OpenSSHTunnelDataAck::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        port_(arena) {}

inline void OpenSSHTunnelDataAck::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.status_ = {};
}
OpenSSHTunnelDataAck::~OpenSSHTunnelDataAck() {
  // @@protoc_insertion_point(destructor:vpn_service.v1.OpenSSHTunnelDataAck)
  SharedDtor(*this);
}
inline void OpenSSHTunnelDataAck::SharedDtor(MessageLite& self) {
  OpenSSHTunnelDataAck& this_ = static_cast<OpenSSHTunnelDataAck&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.port_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL OpenSSHTunnelDataAck::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) OpenSSHTunnelDataAck(arena);
}
constexpr auto OpenSSHTunnelDataAck::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(OpenSSHTunnelDataAck),
                                            alignof(OpenSSHTunnelDataAck));
}
constexpr auto OpenSSHTunnelDataAck::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_OpenSSHTunnelDataAck_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &OpenSSHTunnelDataAck::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<OpenSSHTunnelDataAck>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &OpenSSHTunnelDataAck::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<OpenSSHTunnelDataAck>(), &OpenSSHTunnelDataAck::ByteSizeLong,
              &OpenSSHTunnelDataAck::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(OpenSSHTunnelDataAck, _impl_._cached_size_),
          false,
      },
      &OpenSSHTunnelDataAck::kDescriptorMethods,
      &descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull OpenSSHTunnelDataAck_class_data_ =
        OpenSSHTunnelDataAck::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
OpenSSHTunnelDataAck::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&OpenSSHTunnelDataAck_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(OpenSSHTunnelDataAck_class_data_.tc_table);
  return OpenSSHTunnelDataAck_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 48, 2>
OpenSSHTunnelDataAck::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(OpenSSHTunnelDataAck, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    OpenSSHTunnelDataAck_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::vpn_service::v1::OpenSSHTunnelDataAck>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string port = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(OpenSSHTunnelDataAck, _impl_.port_)}},
    // .vpn_service.v1.Status status = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(OpenSSHTunnelDataAck, _impl_.status_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(OpenSSHTunnelDataAck, _impl_.status_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .vpn_service.v1.Status status = 1;
    {PROTOBUF_FIELD_OFFSET(OpenSSHTunnelDataAck, _impl_.status_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // string port = 2;
    {PROTOBUF_FIELD_OFFSET(OpenSSHTunnelDataAck, _impl_.port_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\43\0\4\0\0\0\0\0"
    "vpn_service.v1.OpenSSHTunnelDataAck"
    "port"
  }},
};
PROTOBUF_NOINLINE void OpenSSHTunnelDataAck::Clear() {
// @@protoc_insertion_point(message_clear_start:vpn_service.v1.OpenSSHTunnelDataAck)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.port_.ClearNonDefaultToEmpty();
  }
  _impl_.status_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL OpenSSHTunnelDataAck::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const OpenSSHTunnelDataAck& this_ = static_cast<const OpenSSHTunnelDataAck&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL OpenSSHTunnelDataAck::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const OpenSSHTunnelDataAck& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:vpn_service.v1.OpenSSHTunnelDataAck)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .vpn_service.v1.Status status = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (this_._internal_status() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_status(), target);
    }
  }

  // string port = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_port().empty()) {
      const ::std::string& _s = this_._internal_port();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "vpn_service.v1.OpenSSHTunnelDataAck.port");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:vpn_service.v1.OpenSSHTunnelDataAck)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t OpenSSHTunnelDataAck::ByteSizeLong(const MessageLite& base) {
  const OpenSSHTunnelDataAck& this_ = static_cast<const OpenSSHTunnelDataAck&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t OpenSSHTunnelDataAck::ByteSizeLong() const {
  const OpenSSHTunnelDataAck& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:vpn_service.v1.OpenSSHTunnelDataAck)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // string port = 2;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_port().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_port());
      }
    }
    // .vpn_service.v1.Status status = 1;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (this_._internal_status() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_status());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void OpenSSHTunnelDataAck::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<OpenSSHTunnelDataAck*>(&to_msg);
  auto& from = static_cast<const OpenSSHTunnelDataAck&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:vpn_service.v1.OpenSSHTunnelDataAck)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_port().empty()) {
        _this->_internal_set_port(from._internal_port());
      } else {
        if (_this->_impl_.port_.IsDefault()) {
          _this->_internal_set_port("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (from._internal_status() != 0) {
        _this->_impl_.status_ = from._impl_.status_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void OpenSSHTunnelDataAck::CopyFrom(const OpenSSHTunnelDataAck& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:vpn_service.v1.OpenSSHTunnelDataAck)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void OpenSSHTunnelDataAck::InternalSwap(OpenSSHTunnelDataAck* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.port_, &other->_impl_.port_, arena);
  swap(_impl_.status_, other->_impl_.status_);
}

::google::protobuf::Metadata OpenSSHTunnelDataAck::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RelayData::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RelayData>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RelayData, _impl_._has_bits_);
};

RelayData::RelayData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RelayData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:vpn_service.v1.RelayData)
}
PROTOBUF_NDEBUG_INLINE RelayData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::vpn_service::v1::RelayData& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        ipv4_(arena, from.ipv4_),
        port_(arena, from.port_),
        method_name_(arena, from.method_name_),
        data_(arena, from.data_) {}

RelayData::RelayData(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RelayData& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RelayData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RelayData* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:vpn_service.v1.RelayData)
}
PROTOBUF_NDEBUG_INLINE RelayData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        ipv4_(arena),
        port_(arena),
        method_name_(arena),
        data_(arena) {}

inline void RelayData::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RelayData::~RelayData() {
  // @@protoc_insertion_point(destructor:vpn_service.v1.RelayData)
  SharedDtor(*this);
}
inline void RelayData::SharedDtor(MessageLite& self) {
  RelayData& this_ = static_cast<RelayData&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.ipv4_.Destroy();
  this_._impl_.port_.Destroy();
  this_._impl_.method_name_.Destroy();
  this_._impl_.data_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RelayData::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RelayData(arena);
}
constexpr auto RelayData::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RelayData),
                                            alignof(RelayData));
}
constexpr auto RelayData::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RelayData_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RelayData::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RelayData>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RelayData::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RelayData>(), &RelayData::ByteSizeLong,
              &RelayData::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RelayData, _impl_._cached_size_),
          false,
      },
      &RelayData::kDescriptorMethods,
      &descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RelayData_class_data_ =
        RelayData::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RelayData::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RelayData_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RelayData_class_data_.tc_table);
  return RelayData_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 52, 2>
RelayData::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RelayData, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RelayData_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::vpn_service::v1::RelayData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes data = 4;
    {::_pbi::TcParser::FastBS1,
     {34, 3, 0, PROTOBUF_FIELD_OFFSET(RelayData, _impl_.data_)}},
    // string ipv4 = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(RelayData, _impl_.ipv4_)}},
    // string port = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(RelayData, _impl_.port_)}},
    // string method_name = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 2, 0, PROTOBUF_FIELD_OFFSET(RelayData, _impl_.method_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string ipv4 = 1;
    {PROTOBUF_FIELD_OFFSET(RelayData, _impl_.ipv4_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string port = 2;
    {PROTOBUF_FIELD_OFFSET(RelayData, _impl_.port_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string method_name = 3;
    {PROTOBUF_FIELD_OFFSET(RelayData, _impl_.method_name_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes data = 4;
    {PROTOBUF_FIELD_OFFSET(RelayData, _impl_.data_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\30\4\4\13\0\0\0\0"
    "vpn_service.v1.RelayData"
    "ipv4"
    "port"
    "method_name"
  }},
};
PROTOBUF_NOINLINE void RelayData::Clear() {
// @@protoc_insertion_point(message_clear_start:vpn_service.v1.RelayData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.ipv4_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _impl_.port_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _impl_.method_name_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      _impl_.data_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RelayData::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RelayData& this_ = static_cast<const RelayData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RelayData::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RelayData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:vpn_service.v1.RelayData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string ipv4 = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_ipv4().empty()) {
      const ::std::string& _s = this_._internal_ipv4();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "vpn_service.v1.RelayData.ipv4");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string port = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (!this_._internal_port().empty()) {
      const ::std::string& _s = this_._internal_port();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "vpn_service.v1.RelayData.port");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // string method_name = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (!this_._internal_method_name().empty()) {
      const ::std::string& _s = this_._internal_method_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "vpn_service.v1.RelayData.method_name");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // bytes data = 4;
  if ((this_._impl_._has_bits_[0] & 0x00000008u) != 0) {
    if (!this_._internal_data().empty()) {
      const ::std::string& _s = this_._internal_data();
      target = stream->WriteBytesMaybeAliased(4, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:vpn_service.v1.RelayData)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RelayData::ByteSizeLong(const MessageLite& base) {
  const RelayData& this_ = static_cast<const RelayData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RelayData::ByteSizeLong() const {
  const RelayData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:vpn_service.v1.RelayData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fu) != 0) {
    // string ipv4 = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_ipv4().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_ipv4());
      }
    }
    // string port = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!this_._internal_port().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_port());
      }
    }
    // string method_name = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (!this_._internal_method_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_method_name());
      }
    }
    // bytes data = 4;
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (!this_._internal_data().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_data());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RelayData::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RelayData*>(&to_msg);
  auto& from = static_cast<const RelayData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:vpn_service.v1.RelayData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_ipv4().empty()) {
        _this->_internal_set_ipv4(from._internal_ipv4());
      } else {
        if (_this->_impl_.ipv4_.IsDefault()) {
          _this->_internal_set_ipv4("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!from._internal_port().empty()) {
        _this->_internal_set_port(from._internal_port());
      } else {
        if (_this->_impl_.port_.IsDefault()) {
          _this->_internal_set_port("");
        }
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (!from._internal_method_name().empty()) {
        _this->_internal_set_method_name(from._internal_method_name());
      } else {
        if (_this->_impl_.method_name_.IsDefault()) {
          _this->_internal_set_method_name("");
        }
      }
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (!from._internal_data().empty()) {
        _this->_internal_set_data(from._internal_data());
      } else {
        if (_this->_impl_.data_.IsDefault()) {
          _this->_internal_set_data("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RelayData::CopyFrom(const RelayData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:vpn_service.v1.RelayData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RelayData::InternalSwap(RelayData* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ipv4_, &other->_impl_.ipv4_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.port_, &other->_impl_.port_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.method_name_, &other->_impl_.method_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_, &other->_impl_.data_, arena);
}

::google::protobuf::Metadata RelayData::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RelayDataAck::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RelayDataAck>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RelayDataAck, _impl_._has_bits_);
};

RelayDataAck::RelayDataAck(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RelayDataAck_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:vpn_service.v1.RelayDataAck)
}
PROTOBUF_NDEBUG_INLINE RelayDataAck::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::vpn_service::v1::RelayDataAck& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        response_(arena, from.response_) {}

RelayDataAck::RelayDataAck(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RelayDataAck& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RelayDataAck_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RelayDataAck* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.status_ = from._impl_.status_;

  // @@protoc_insertion_point(copy_constructor:vpn_service.v1.RelayDataAck)
}
PROTOBUF_NDEBUG_INLINE RelayDataAck::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        response_(arena) {}

inline void RelayDataAck::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.status_ = {};
}
RelayDataAck::~RelayDataAck() {
  // @@protoc_insertion_point(destructor:vpn_service.v1.RelayDataAck)
  SharedDtor(*this);
}
inline void RelayDataAck::SharedDtor(MessageLite& self) {
  RelayDataAck& this_ = static_cast<RelayDataAck&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.response_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RelayDataAck::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RelayDataAck(arena);
}
constexpr auto RelayDataAck::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RelayDataAck),
                                            alignof(RelayDataAck));
}
constexpr auto RelayDataAck::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RelayDataAck_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RelayDataAck::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RelayDataAck>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RelayDataAck::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RelayDataAck>(), &RelayDataAck::ByteSizeLong,
              &RelayDataAck::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RelayDataAck, _impl_._cached_size_),
          false,
      },
      &RelayDataAck::kDescriptorMethods,
      &descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RelayDataAck_class_data_ =
        RelayDataAck::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RelayDataAck::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RelayDataAck_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RelayDataAck_class_data_.tc_table);
  return RelayDataAck_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
RelayDataAck::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RelayDataAck, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RelayDataAck_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::vpn_service::v1::RelayDataAck>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes response = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(RelayDataAck, _impl_.response_)}},
    // .vpn_service.v1.Status status = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RelayDataAck, _impl_.status_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(RelayDataAck, _impl_.status_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .vpn_service.v1.Status status = 1;
    {PROTOBUF_FIELD_OFFSET(RelayDataAck, _impl_.status_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // bytes response = 2;
    {PROTOBUF_FIELD_OFFSET(RelayDataAck, _impl_.response_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void RelayDataAck::Clear() {
// @@protoc_insertion_point(message_clear_start:vpn_service.v1.RelayDataAck)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.response_.ClearNonDefaultToEmpty();
  }
  _impl_.status_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RelayDataAck::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RelayDataAck& this_ = static_cast<const RelayDataAck&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RelayDataAck::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RelayDataAck& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:vpn_service.v1.RelayDataAck)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .vpn_service.v1.Status status = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (this_._internal_status() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_status(), target);
    }
  }

  // bytes response = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_response().empty()) {
      const ::std::string& _s = this_._internal_response();
      target = stream->WriteBytesMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:vpn_service.v1.RelayDataAck)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RelayDataAck::ByteSizeLong(const MessageLite& base) {
  const RelayDataAck& this_ = static_cast<const RelayDataAck&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RelayDataAck::ByteSizeLong() const {
  const RelayDataAck& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:vpn_service.v1.RelayDataAck)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // bytes response = 2;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_response().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_response());
      }
    }
    // .vpn_service.v1.Status status = 1;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (this_._internal_status() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_status());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RelayDataAck::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RelayDataAck*>(&to_msg);
  auto& from = static_cast<const RelayDataAck&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:vpn_service.v1.RelayDataAck)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_response().empty()) {
        _this->_internal_set_response(from._internal_response());
      } else {
        if (_this->_impl_.response_.IsDefault()) {
          _this->_internal_set_response("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (from._internal_status() != 0) {
        _this->_impl_.status_ = from._impl_.status_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RelayDataAck::CopyFrom(const RelayDataAck& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:vpn_service.v1.RelayDataAck)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RelayDataAck::InternalSwap(RelayDataAck* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.response_, &other->_impl_.response_, arena);
  swap(_impl_.status_, other->_impl_.status_);
}

::google::protobuf::Metadata RelayDataAck::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace vpn_service
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
