// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: infra_service/vpn_service.proto
// Protobuf C++ Version: 6.31.1

#ifndef infra_5fservice_2fvpn_5fservice_2eproto_2epb_2eh
#define infra_5fservice_2fvpn_5fservice_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_infra_5fservice_2fvpn_5fservice_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_infra_5fservice_2fvpn_5fservice_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_infra_5fservice_2fvpn_5fservice_2eproto;
}  // extern "C"
namespace vpn_service {
namespace v1 {
enum Status : int;
extern const uint32_t Status_internal_data_[];
class CreateVPNClientData;
struct CreateVPNClientDataDefaultTypeInternal;
extern CreateVPNClientDataDefaultTypeInternal _CreateVPNClientData_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CreateVPNClientData_class_data_;
class CreateVPNClientDataAck;
struct CreateVPNClientDataAckDefaultTypeInternal;
extern CreateVPNClientDataAckDefaultTypeInternal _CreateVPNClientDataAck_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CreateVPNClientDataAck_class_data_;
class OpenSSHTunnelData;
struct OpenSSHTunnelDataDefaultTypeInternal;
extern OpenSSHTunnelDataDefaultTypeInternal _OpenSSHTunnelData_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull OpenSSHTunnelData_class_data_;
class OpenSSHTunnelDataAck;
struct OpenSSHTunnelDataAckDefaultTypeInternal;
extern OpenSSHTunnelDataAckDefaultTypeInternal _OpenSSHTunnelDataAck_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull OpenSSHTunnelDataAck_class_data_;
class RelayData;
struct RelayDataDefaultTypeInternal;
extern RelayDataDefaultTypeInternal _RelayData_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RelayData_class_data_;
class RelayDataAck;
struct RelayDataAckDefaultTypeInternal;
extern RelayDataAckDefaultTypeInternal _RelayDataAck_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RelayDataAck_class_data_;
}  // namespace v1
}  // namespace vpn_service
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::vpn_service::v1::Status_internal_data_>
    internal::EnumTraitsImpl::value<::vpn_service::v1::Status>;
}  // namespace protobuf
}  // namespace google

namespace vpn_service {
namespace v1 {
enum Status : int {
  SUCCESS = 0,
  FAILED = 1,
  CONNECTION_TIMEOUT = 2,
  SSH_FAILED = 3,
  Status_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  Status_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t Status_internal_data_[];
inline constexpr Status Status_MIN =
    static_cast<Status>(0);
inline constexpr Status Status_MAX =
    static_cast<Status>(3);
inline bool Status_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int Status_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Status_descriptor();
template <typename T>
const ::std::string& Status_Name(T value) {
  static_assert(::std::is_same<T, Status>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Status_Name().");
  return Status_Name(static_cast<Status>(value));
}
template <>
inline const ::std::string& Status_Name(Status value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Status_descriptor, 0, 3>(
      static_cast<int>(value));
}
inline bool Status_Parse(
    ::absl::string_view name, Status* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Status>(Status_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class RelayDataAck final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:vpn_service.v1.RelayDataAck) */ {
 public:
  inline RelayDataAck() : RelayDataAck(nullptr) {}
  ~RelayDataAck() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RelayDataAck* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RelayDataAck));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RelayDataAck(::google::protobuf::internal::ConstantInitialized);

  inline RelayDataAck(const RelayDataAck& from) : RelayDataAck(nullptr, from) {}
  inline RelayDataAck(RelayDataAck&& from) noexcept
      : RelayDataAck(nullptr, ::std::move(from)) {}
  inline RelayDataAck& operator=(const RelayDataAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline RelayDataAck& operator=(RelayDataAck&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RelayDataAck& default_instance() {
    return *reinterpret_cast<const RelayDataAck*>(
        &_RelayDataAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(RelayDataAck& a, RelayDataAck& b) { a.Swap(&b); }
  inline void Swap(RelayDataAck* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RelayDataAck* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RelayDataAck* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RelayDataAck>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RelayDataAck& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RelayDataAck& from) { RelayDataAck::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RelayDataAck* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "vpn_service.v1.RelayDataAck"; }

 protected:
  explicit RelayDataAck(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RelayDataAck(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RelayDataAck& from);
  RelayDataAck(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RelayDataAck&& from) noexcept
      : RelayDataAck(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kResponseFieldNumber = 2,
    kStatusFieldNumber = 1,
  };
  // bytes response = 2;
  void clear_response() ;
  const ::std::string& response() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_response(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_response();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_response();
  void set_allocated_response(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_response() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_response(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_response();

  public:
  // .vpn_service.v1.Status status = 1;
  void clear_status() ;
  ::vpn_service::v1::Status status() const;
  void set_status(::vpn_service::v1::Status value);

  private:
  ::vpn_service::v1::Status _internal_status() const;
  void _internal_set_status(::vpn_service::v1::Status value);

  public:
  // @@protoc_insertion_point(class_scope:vpn_service.v1.RelayDataAck)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RelayDataAck& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr response_;
    int status_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_infra_5fservice_2fvpn_5fservice_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RelayDataAck_class_data_;
// -------------------------------------------------------------------

class RelayData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:vpn_service.v1.RelayData) */ {
 public:
  inline RelayData() : RelayData(nullptr) {}
  ~RelayData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RelayData* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RelayData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RelayData(::google::protobuf::internal::ConstantInitialized);

  inline RelayData(const RelayData& from) : RelayData(nullptr, from) {}
  inline RelayData(RelayData&& from) noexcept
      : RelayData(nullptr, ::std::move(from)) {}
  inline RelayData& operator=(const RelayData& from) {
    CopyFrom(from);
    return *this;
  }
  inline RelayData& operator=(RelayData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RelayData& default_instance() {
    return *reinterpret_cast<const RelayData*>(
        &_RelayData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(RelayData& a, RelayData& b) { a.Swap(&b); }
  inline void Swap(RelayData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RelayData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RelayData* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RelayData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RelayData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RelayData& from) { RelayData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RelayData* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "vpn_service.v1.RelayData"; }

 protected:
  explicit RelayData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RelayData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RelayData& from);
  RelayData(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RelayData&& from) noexcept
      : RelayData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIpv4FieldNumber = 1,
    kPortFieldNumber = 2,
    kMethodNameFieldNumber = 3,
    kDataFieldNumber = 4,
  };
  // string ipv4 = 1;
  void clear_ipv4() ;
  const ::std::string& ipv4() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_ipv4(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_ipv4();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_ipv4();
  void set_allocated_ipv4(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_ipv4() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_ipv4(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_ipv4();

  public:
  // string port = 2;
  void clear_port() ;
  const ::std::string& port() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_port(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_port();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_port();
  void set_allocated_port(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_port() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_port(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_port();

  public:
  // string method_name = 3;
  void clear_method_name() ;
  const ::std::string& method_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_method_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_method_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_method_name();
  void set_allocated_method_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_method_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_method_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_method_name();

  public:
  // bytes data = 4;
  void clear_data() ;
  const ::std::string& data() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_data();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_data();
  void set_allocated_data(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_data() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_data(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_data();

  public:
  // @@protoc_insertion_point(class_scope:vpn_service.v1.RelayData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 52,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RelayData& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr ipv4_;
    ::google::protobuf::internal::ArenaStringPtr port_;
    ::google::protobuf::internal::ArenaStringPtr method_name_;
    ::google::protobuf::internal::ArenaStringPtr data_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_infra_5fservice_2fvpn_5fservice_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RelayData_class_data_;
// -------------------------------------------------------------------

class OpenSSHTunnelDataAck final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:vpn_service.v1.OpenSSHTunnelDataAck) */ {
 public:
  inline OpenSSHTunnelDataAck() : OpenSSHTunnelDataAck(nullptr) {}
  ~OpenSSHTunnelDataAck() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(OpenSSHTunnelDataAck* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(OpenSSHTunnelDataAck));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR OpenSSHTunnelDataAck(::google::protobuf::internal::ConstantInitialized);

  inline OpenSSHTunnelDataAck(const OpenSSHTunnelDataAck& from) : OpenSSHTunnelDataAck(nullptr, from) {}
  inline OpenSSHTunnelDataAck(OpenSSHTunnelDataAck&& from) noexcept
      : OpenSSHTunnelDataAck(nullptr, ::std::move(from)) {}
  inline OpenSSHTunnelDataAck& operator=(const OpenSSHTunnelDataAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline OpenSSHTunnelDataAck& operator=(OpenSSHTunnelDataAck&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OpenSSHTunnelDataAck& default_instance() {
    return *reinterpret_cast<const OpenSSHTunnelDataAck*>(
        &_OpenSSHTunnelDataAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(OpenSSHTunnelDataAck& a, OpenSSHTunnelDataAck& b) { a.Swap(&b); }
  inline void Swap(OpenSSHTunnelDataAck* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OpenSSHTunnelDataAck* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OpenSSHTunnelDataAck* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<OpenSSHTunnelDataAck>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const OpenSSHTunnelDataAck& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const OpenSSHTunnelDataAck& from) { OpenSSHTunnelDataAck::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(OpenSSHTunnelDataAck* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "vpn_service.v1.OpenSSHTunnelDataAck"; }

 protected:
  explicit OpenSSHTunnelDataAck(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  OpenSSHTunnelDataAck(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const OpenSSHTunnelDataAck& from);
  OpenSSHTunnelDataAck(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, OpenSSHTunnelDataAck&& from) noexcept
      : OpenSSHTunnelDataAck(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPortFieldNumber = 2,
    kStatusFieldNumber = 1,
  };
  // string port = 2;
  void clear_port() ;
  const ::std::string& port() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_port(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_port();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_port();
  void set_allocated_port(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_port() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_port(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_port();

  public:
  // .vpn_service.v1.Status status = 1;
  void clear_status() ;
  ::vpn_service::v1::Status status() const;
  void set_status(::vpn_service::v1::Status value);

  private:
  ::vpn_service::v1::Status _internal_status() const;
  void _internal_set_status(::vpn_service::v1::Status value);

  public:
  // @@protoc_insertion_point(class_scope:vpn_service.v1.OpenSSHTunnelDataAck)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 48,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const OpenSSHTunnelDataAck& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr port_;
    int status_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_infra_5fservice_2fvpn_5fservice_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull OpenSSHTunnelDataAck_class_data_;
// -------------------------------------------------------------------

class OpenSSHTunnelData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:vpn_service.v1.OpenSSHTunnelData) */ {
 public:
  inline OpenSSHTunnelData() : OpenSSHTunnelData(nullptr) {}
  ~OpenSSHTunnelData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(OpenSSHTunnelData* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(OpenSSHTunnelData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR OpenSSHTunnelData(::google::protobuf::internal::ConstantInitialized);

  inline OpenSSHTunnelData(const OpenSSHTunnelData& from) : OpenSSHTunnelData(nullptr, from) {}
  inline OpenSSHTunnelData(OpenSSHTunnelData&& from) noexcept
      : OpenSSHTunnelData(nullptr, ::std::move(from)) {}
  inline OpenSSHTunnelData& operator=(const OpenSSHTunnelData& from) {
    CopyFrom(from);
    return *this;
  }
  inline OpenSSHTunnelData& operator=(OpenSSHTunnelData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OpenSSHTunnelData& default_instance() {
    return *reinterpret_cast<const OpenSSHTunnelData*>(
        &_OpenSSHTunnelData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(OpenSSHTunnelData& a, OpenSSHTunnelData& b) { a.Swap(&b); }
  inline void Swap(OpenSSHTunnelData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OpenSSHTunnelData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OpenSSHTunnelData* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<OpenSSHTunnelData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const OpenSSHTunnelData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const OpenSSHTunnelData& from) { OpenSSHTunnelData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(OpenSSHTunnelData* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "vpn_service.v1.OpenSSHTunnelData"; }

 protected:
  explicit OpenSSHTunnelData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  OpenSSHTunnelData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const OpenSSHTunnelData& from);
  OpenSSHTunnelData(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, OpenSSHTunnelData&& from) noexcept
      : OpenSSHTunnelData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIpv4FieldNumber = 1,
    kPortFieldNumber = 2,
    kKeyFieldNumber = 3,
  };
  // string ipv4 = 1;
  void clear_ipv4() ;
  const ::std::string& ipv4() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_ipv4(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_ipv4();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_ipv4();
  void set_allocated_ipv4(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_ipv4() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_ipv4(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_ipv4();

  public:
  // string port = 2;
  void clear_port() ;
  const ::std::string& port() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_port(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_port();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_port();
  void set_allocated_port(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_port() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_port(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_port();

  public:
  // string key = 3;
  void clear_key() ;
  const ::std::string& key() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_key(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_key();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_key();
  void set_allocated_key(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_key() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_key(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_key();

  public:
  // @@protoc_insertion_point(class_scope:vpn_service.v1.OpenSSHTunnelData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 52,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const OpenSSHTunnelData& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr ipv4_;
    ::google::protobuf::internal::ArenaStringPtr port_;
    ::google::protobuf::internal::ArenaStringPtr key_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_infra_5fservice_2fvpn_5fservice_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull OpenSSHTunnelData_class_data_;
// -------------------------------------------------------------------

class CreateVPNClientDataAck final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:vpn_service.v1.CreateVPNClientDataAck) */ {
 public:
  inline CreateVPNClientDataAck() : CreateVPNClientDataAck(nullptr) {}
  ~CreateVPNClientDataAck() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CreateVPNClientDataAck* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CreateVPNClientDataAck));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CreateVPNClientDataAck(::google::protobuf::internal::ConstantInitialized);

  inline CreateVPNClientDataAck(const CreateVPNClientDataAck& from) : CreateVPNClientDataAck(nullptr, from) {}
  inline CreateVPNClientDataAck(CreateVPNClientDataAck&& from) noexcept
      : CreateVPNClientDataAck(nullptr, ::std::move(from)) {}
  inline CreateVPNClientDataAck& operator=(const CreateVPNClientDataAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline CreateVPNClientDataAck& operator=(CreateVPNClientDataAck&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CreateVPNClientDataAck& default_instance() {
    return *reinterpret_cast<const CreateVPNClientDataAck*>(
        &_CreateVPNClientDataAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(CreateVPNClientDataAck& a, CreateVPNClientDataAck& b) { a.Swap(&b); }
  inline void Swap(CreateVPNClientDataAck* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CreateVPNClientDataAck* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CreateVPNClientDataAck* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CreateVPNClientDataAck>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CreateVPNClientDataAck& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CreateVPNClientDataAck& from) { CreateVPNClientDataAck::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CreateVPNClientDataAck* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "vpn_service.v1.CreateVPNClientDataAck"; }

 protected:
  explicit CreateVPNClientDataAck(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CreateVPNClientDataAck(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CreateVPNClientDataAck& from);
  CreateVPNClientDataAck(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CreateVPNClientDataAck&& from) noexcept
      : CreateVPNClientDataAck(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFilenameFieldNumber = 2,
    kContentFieldNumber = 3,
    kStatusFieldNumber = 1,
  };
  // string filename = 2;
  void clear_filename() ;
  const ::std::string& filename() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_filename(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_filename();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_filename();
  void set_allocated_filename(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_filename() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_filename(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_filename();

  public:
  // bytes content = 3;
  void clear_content() ;
  const ::std::string& content() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_content(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_content();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_content();
  void set_allocated_content(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_content() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_content(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_content();

  public:
  // .vpn_service.v1.Status status = 1;
  void clear_status() ;
  ::vpn_service::v1::Status status() const;
  void set_status(::vpn_service::v1::Status value);

  private:
  ::vpn_service::v1::Status _internal_status() const;
  void _internal_set_status(::vpn_service::v1::Status value);

  public:
  // @@protoc_insertion_point(class_scope:vpn_service.v1.CreateVPNClientDataAck)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 54,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CreateVPNClientDataAck& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr filename_;
    ::google::protobuf::internal::ArenaStringPtr content_;
    int status_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_infra_5fservice_2fvpn_5fservice_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CreateVPNClientDataAck_class_data_;
// -------------------------------------------------------------------

class CreateVPNClientData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:vpn_service.v1.CreateVPNClientData) */ {
 public:
  inline CreateVPNClientData() : CreateVPNClientData(nullptr) {}
  ~CreateVPNClientData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CreateVPNClientData* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CreateVPNClientData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CreateVPNClientData(::google::protobuf::internal::ConstantInitialized);

  inline CreateVPNClientData(const CreateVPNClientData& from) : CreateVPNClientData(nullptr, from) {}
  inline CreateVPNClientData(CreateVPNClientData&& from) noexcept
      : CreateVPNClientData(nullptr, ::std::move(from)) {}
  inline CreateVPNClientData& operator=(const CreateVPNClientData& from) {
    CopyFrom(from);
    return *this;
  }
  inline CreateVPNClientData& operator=(CreateVPNClientData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CreateVPNClientData& default_instance() {
    return *reinterpret_cast<const CreateVPNClientData*>(
        &_CreateVPNClientData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CreateVPNClientData& a, CreateVPNClientData& b) { a.Swap(&b); }
  inline void Swap(CreateVPNClientData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CreateVPNClientData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CreateVPNClientData* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CreateVPNClientData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CreateVPNClientData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CreateVPNClientData& from) { CreateVPNClientData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CreateVPNClientData* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "vpn_service.v1.CreateVPNClientData"; }

 protected:
  explicit CreateVPNClientData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CreateVPNClientData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CreateVPNClientData& from);
  CreateVPNClientData(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CreateVPNClientData&& from) noexcept
      : CreateVPNClientData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kClientNameFieldNumber = 1,
  };
  // string client_name = 1;
  void clear_client_name() ;
  const ::std::string& client_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_client_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_client_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_client_name();
  void set_allocated_client_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_client_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_client_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_client_name();

  public:
  // @@protoc_insertion_point(class_scope:vpn_service.v1.CreateVPNClientData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 54,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CreateVPNClientData& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr client_name_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_infra_5fservice_2fvpn_5fservice_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CreateVPNClientData_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CreateVPNClientData

// string client_name = 1;
inline void CreateVPNClientData::clear_client_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.client_name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& CreateVPNClientData::client_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:vpn_service.v1.CreateVPNClientData.client_name)
  return _internal_client_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CreateVPNClientData::set_client_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.client_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:vpn_service.v1.CreateVPNClientData.client_name)
}
inline ::std::string* PROTOBUF_NONNULL CreateVPNClientData::mutable_client_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_client_name();
  // @@protoc_insertion_point(field_mutable:vpn_service.v1.CreateVPNClientData.client_name)
  return _s;
}
inline const ::std::string& CreateVPNClientData::_internal_client_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.client_name_.Get();
}
inline void CreateVPNClientData::_internal_set_client_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.client_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CreateVPNClientData::_internal_mutable_client_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.client_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CreateVPNClientData::release_client_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:vpn_service.v1.CreateVPNClientData.client_name)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.client_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.client_name_.Set("", GetArena());
  }
  return released;
}
inline void CreateVPNClientData::set_allocated_client_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.client_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.client_name_.IsDefault()) {
    _impl_.client_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:vpn_service.v1.CreateVPNClientData.client_name)
}

// -------------------------------------------------------------------

// CreateVPNClientDataAck

// .vpn_service.v1.Status status = 1;
inline void CreateVPNClientDataAck::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::vpn_service::v1::Status CreateVPNClientDataAck::status() const {
  // @@protoc_insertion_point(field_get:vpn_service.v1.CreateVPNClientDataAck.status)
  return _internal_status();
}
inline void CreateVPNClientDataAck::set_status(::vpn_service::v1::Status value) {
  _internal_set_status(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:vpn_service.v1.CreateVPNClientDataAck.status)
}
inline ::vpn_service::v1::Status CreateVPNClientDataAck::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::vpn_service::v1::Status>(_impl_.status_);
}
inline void CreateVPNClientDataAck::_internal_set_status(::vpn_service::v1::Status value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

// string filename = 2;
inline void CreateVPNClientDataAck::clear_filename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filename_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& CreateVPNClientDataAck::filename() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:vpn_service.v1.CreateVPNClientDataAck.filename)
  return _internal_filename();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CreateVPNClientDataAck::set_filename(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.filename_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:vpn_service.v1.CreateVPNClientDataAck.filename)
}
inline ::std::string* PROTOBUF_NONNULL CreateVPNClientDataAck::mutable_filename()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_filename();
  // @@protoc_insertion_point(field_mutable:vpn_service.v1.CreateVPNClientDataAck.filename)
  return _s;
}
inline const ::std::string& CreateVPNClientDataAck::_internal_filename() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.filename_.Get();
}
inline void CreateVPNClientDataAck::_internal_set_filename(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.filename_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CreateVPNClientDataAck::_internal_mutable_filename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.filename_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CreateVPNClientDataAck::release_filename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:vpn_service.v1.CreateVPNClientDataAck.filename)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.filename_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.filename_.Set("", GetArena());
  }
  return released;
}
inline void CreateVPNClientDataAck::set_allocated_filename(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.filename_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.filename_.IsDefault()) {
    _impl_.filename_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:vpn_service.v1.CreateVPNClientDataAck.filename)
}

// bytes content = 3;
inline void CreateVPNClientDataAck::clear_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.content_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::std::string& CreateVPNClientDataAck::content() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:vpn_service.v1.CreateVPNClientDataAck.content)
  return _internal_content();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CreateVPNClientDataAck::set_content(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.content_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:vpn_service.v1.CreateVPNClientDataAck.content)
}
inline ::std::string* PROTOBUF_NONNULL CreateVPNClientDataAck::mutable_content()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_content();
  // @@protoc_insertion_point(field_mutable:vpn_service.v1.CreateVPNClientDataAck.content)
  return _s;
}
inline const ::std::string& CreateVPNClientDataAck::_internal_content() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.content_.Get();
}
inline void CreateVPNClientDataAck::_internal_set_content(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.content_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CreateVPNClientDataAck::_internal_mutable_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.content_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CreateVPNClientDataAck::release_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:vpn_service.v1.CreateVPNClientDataAck.content)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.content_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.content_.Set("", GetArena());
  }
  return released;
}
inline void CreateVPNClientDataAck::set_allocated_content(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.content_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.content_.IsDefault()) {
    _impl_.content_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:vpn_service.v1.CreateVPNClientDataAck.content)
}

// -------------------------------------------------------------------

// OpenSSHTunnelData

// string ipv4 = 1;
inline void OpenSSHTunnelData::clear_ipv4() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ipv4_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& OpenSSHTunnelData::ipv4() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:vpn_service.v1.OpenSSHTunnelData.ipv4)
  return _internal_ipv4();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void OpenSSHTunnelData::set_ipv4(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.ipv4_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:vpn_service.v1.OpenSSHTunnelData.ipv4)
}
inline ::std::string* PROTOBUF_NONNULL OpenSSHTunnelData::mutable_ipv4()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_ipv4();
  // @@protoc_insertion_point(field_mutable:vpn_service.v1.OpenSSHTunnelData.ipv4)
  return _s;
}
inline const ::std::string& OpenSSHTunnelData::_internal_ipv4() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ipv4_.Get();
}
inline void OpenSSHTunnelData::_internal_set_ipv4(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.ipv4_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL OpenSSHTunnelData::_internal_mutable_ipv4() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.ipv4_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE OpenSSHTunnelData::release_ipv4() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:vpn_service.v1.OpenSSHTunnelData.ipv4)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.ipv4_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.ipv4_.Set("", GetArena());
  }
  return released;
}
inline void OpenSSHTunnelData::set_allocated_ipv4(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.ipv4_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.ipv4_.IsDefault()) {
    _impl_.ipv4_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:vpn_service.v1.OpenSSHTunnelData.ipv4)
}

// string port = 2;
inline void OpenSSHTunnelData::clear_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::std::string& OpenSSHTunnelData::port() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:vpn_service.v1.OpenSSHTunnelData.port)
  return _internal_port();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void OpenSSHTunnelData::set_port(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.port_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:vpn_service.v1.OpenSSHTunnelData.port)
}
inline ::std::string* PROTOBUF_NONNULL OpenSSHTunnelData::mutable_port()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_port();
  // @@protoc_insertion_point(field_mutable:vpn_service.v1.OpenSSHTunnelData.port)
  return _s;
}
inline const ::std::string& OpenSSHTunnelData::_internal_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.port_.Get();
}
inline void OpenSSHTunnelData::_internal_set_port(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.port_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL OpenSSHTunnelData::_internal_mutable_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.port_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE OpenSSHTunnelData::release_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:vpn_service.v1.OpenSSHTunnelData.port)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.port_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.port_.Set("", GetArena());
  }
  return released;
}
inline void OpenSSHTunnelData::set_allocated_port(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.port_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.port_.IsDefault()) {
    _impl_.port_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:vpn_service.v1.OpenSSHTunnelData.port)
}

// string key = 3;
inline void OpenSSHTunnelData::clear_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.key_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const ::std::string& OpenSSHTunnelData::key() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:vpn_service.v1.OpenSSHTunnelData.key)
  return _internal_key();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void OpenSSHTunnelData::set_key(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.key_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:vpn_service.v1.OpenSSHTunnelData.key)
}
inline ::std::string* PROTOBUF_NONNULL OpenSSHTunnelData::mutable_key()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_key();
  // @@protoc_insertion_point(field_mutable:vpn_service.v1.OpenSSHTunnelData.key)
  return _s;
}
inline const ::std::string& OpenSSHTunnelData::_internal_key() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.key_.Get();
}
inline void OpenSSHTunnelData::_internal_set_key(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.key_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL OpenSSHTunnelData::_internal_mutable_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.key_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE OpenSSHTunnelData::release_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:vpn_service.v1.OpenSSHTunnelData.key)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.key_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.key_.Set("", GetArena());
  }
  return released;
}
inline void OpenSSHTunnelData::set_allocated_key(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.key_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.key_.IsDefault()) {
    _impl_.key_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:vpn_service.v1.OpenSSHTunnelData.key)
}

// -------------------------------------------------------------------

// OpenSSHTunnelDataAck

// .vpn_service.v1.Status status = 1;
inline void OpenSSHTunnelDataAck::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::vpn_service::v1::Status OpenSSHTunnelDataAck::status() const {
  // @@protoc_insertion_point(field_get:vpn_service.v1.OpenSSHTunnelDataAck.status)
  return _internal_status();
}
inline void OpenSSHTunnelDataAck::set_status(::vpn_service::v1::Status value) {
  _internal_set_status(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:vpn_service.v1.OpenSSHTunnelDataAck.status)
}
inline ::vpn_service::v1::Status OpenSSHTunnelDataAck::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::vpn_service::v1::Status>(_impl_.status_);
}
inline void OpenSSHTunnelDataAck::_internal_set_status(::vpn_service::v1::Status value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

// string port = 2;
inline void OpenSSHTunnelDataAck::clear_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& OpenSSHTunnelDataAck::port() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:vpn_service.v1.OpenSSHTunnelDataAck.port)
  return _internal_port();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void OpenSSHTunnelDataAck::set_port(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.port_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:vpn_service.v1.OpenSSHTunnelDataAck.port)
}
inline ::std::string* PROTOBUF_NONNULL OpenSSHTunnelDataAck::mutable_port()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_port();
  // @@protoc_insertion_point(field_mutable:vpn_service.v1.OpenSSHTunnelDataAck.port)
  return _s;
}
inline const ::std::string& OpenSSHTunnelDataAck::_internal_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.port_.Get();
}
inline void OpenSSHTunnelDataAck::_internal_set_port(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.port_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL OpenSSHTunnelDataAck::_internal_mutable_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.port_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE OpenSSHTunnelDataAck::release_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:vpn_service.v1.OpenSSHTunnelDataAck.port)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.port_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.port_.Set("", GetArena());
  }
  return released;
}
inline void OpenSSHTunnelDataAck::set_allocated_port(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.port_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.port_.IsDefault()) {
    _impl_.port_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:vpn_service.v1.OpenSSHTunnelDataAck.port)
}

// -------------------------------------------------------------------

// RelayData

// string ipv4 = 1;
inline void RelayData::clear_ipv4() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ipv4_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& RelayData::ipv4() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:vpn_service.v1.RelayData.ipv4)
  return _internal_ipv4();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RelayData::set_ipv4(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.ipv4_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:vpn_service.v1.RelayData.ipv4)
}
inline ::std::string* PROTOBUF_NONNULL RelayData::mutable_ipv4()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_ipv4();
  // @@protoc_insertion_point(field_mutable:vpn_service.v1.RelayData.ipv4)
  return _s;
}
inline const ::std::string& RelayData::_internal_ipv4() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ipv4_.Get();
}
inline void RelayData::_internal_set_ipv4(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.ipv4_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RelayData::_internal_mutable_ipv4() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.ipv4_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RelayData::release_ipv4() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:vpn_service.v1.RelayData.ipv4)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.ipv4_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.ipv4_.Set("", GetArena());
  }
  return released;
}
inline void RelayData::set_allocated_ipv4(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.ipv4_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.ipv4_.IsDefault()) {
    _impl_.ipv4_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:vpn_service.v1.RelayData.ipv4)
}

// string port = 2;
inline void RelayData::clear_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::std::string& RelayData::port() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:vpn_service.v1.RelayData.port)
  return _internal_port();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RelayData::set_port(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.port_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:vpn_service.v1.RelayData.port)
}
inline ::std::string* PROTOBUF_NONNULL RelayData::mutable_port()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_port();
  // @@protoc_insertion_point(field_mutable:vpn_service.v1.RelayData.port)
  return _s;
}
inline const ::std::string& RelayData::_internal_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.port_.Get();
}
inline void RelayData::_internal_set_port(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.port_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RelayData::_internal_mutable_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.port_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RelayData::release_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:vpn_service.v1.RelayData.port)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.port_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.port_.Set("", GetArena());
  }
  return released;
}
inline void RelayData::set_allocated_port(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.port_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.port_.IsDefault()) {
    _impl_.port_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:vpn_service.v1.RelayData.port)
}

// string method_name = 3;
inline void RelayData::clear_method_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.method_name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const ::std::string& RelayData::method_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:vpn_service.v1.RelayData.method_name)
  return _internal_method_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RelayData::set_method_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.method_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:vpn_service.v1.RelayData.method_name)
}
inline ::std::string* PROTOBUF_NONNULL RelayData::mutable_method_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_method_name();
  // @@protoc_insertion_point(field_mutable:vpn_service.v1.RelayData.method_name)
  return _s;
}
inline const ::std::string& RelayData::_internal_method_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.method_name_.Get();
}
inline void RelayData::_internal_set_method_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.method_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RelayData::_internal_mutable_method_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.method_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RelayData::release_method_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:vpn_service.v1.RelayData.method_name)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.method_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.method_name_.Set("", GetArena());
  }
  return released;
}
inline void RelayData::set_allocated_method_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.method_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.method_name_.IsDefault()) {
    _impl_.method_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:vpn_service.v1.RelayData.method_name)
}

// bytes data = 4;
inline void RelayData::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const ::std::string& RelayData::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:vpn_service.v1.RelayData.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RelayData::set_data(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:vpn_service.v1.RelayData.data)
}
inline ::std::string* PROTOBUF_NONNULL RelayData::mutable_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:vpn_service.v1.RelayData.data)
  return _s;
}
inline const ::std::string& RelayData::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void RelayData::_internal_set_data(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.data_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RelayData::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  return _impl_.data_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RelayData::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:vpn_service.v1.RelayData.data)
  if ((_impl_._has_bits_[0] & 0x00000008u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000008u;
  auto* released = _impl_.data_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.data_.Set("", GetArena());
  }
  return released;
}
inline void RelayData::set_allocated_data(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:vpn_service.v1.RelayData.data)
}

// -------------------------------------------------------------------

// RelayDataAck

// .vpn_service.v1.Status status = 1;
inline void RelayDataAck::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::vpn_service::v1::Status RelayDataAck::status() const {
  // @@protoc_insertion_point(field_get:vpn_service.v1.RelayDataAck.status)
  return _internal_status();
}
inline void RelayDataAck::set_status(::vpn_service::v1::Status value) {
  _internal_set_status(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:vpn_service.v1.RelayDataAck.status)
}
inline ::vpn_service::v1::Status RelayDataAck::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::vpn_service::v1::Status>(_impl_.status_);
}
inline void RelayDataAck::_internal_set_status(::vpn_service::v1::Status value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

// bytes response = 2;
inline void RelayDataAck::clear_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.response_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& RelayDataAck::response() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:vpn_service.v1.RelayDataAck.response)
  return _internal_response();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RelayDataAck::set_response(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.response_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:vpn_service.v1.RelayDataAck.response)
}
inline ::std::string* PROTOBUF_NONNULL RelayDataAck::mutable_response()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_response();
  // @@protoc_insertion_point(field_mutable:vpn_service.v1.RelayDataAck.response)
  return _s;
}
inline const ::std::string& RelayDataAck::_internal_response() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.response_.Get();
}
inline void RelayDataAck::_internal_set_response(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.response_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RelayDataAck::_internal_mutable_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.response_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RelayDataAck::release_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:vpn_service.v1.RelayDataAck.response)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.response_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.response_.Set("", GetArena());
  }
  return released;
}
inline void RelayDataAck::set_allocated_response(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.response_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.response_.IsDefault()) {
    _impl_.response_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:vpn_service.v1.RelayDataAck.response)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace vpn_service


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::vpn_service::v1::Status> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::vpn_service::v1::Status>() {
  return ::vpn_service::v1::Status_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // infra_5fservice_2fvpn_5fservice_2eproto_2epb_2eh
