// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: infra_service/vpn_service.proto

#include "infra_service/vpn_service.pb.h"
#include "infra_service/vpn_service.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace vpn_service {
namespace v1 {

static const char* VPNService_method_names[] = {
  "/vpn_service.v1.VPNService/CreateVPNClient",
  "/vpn_service.v1.VPNService/OpenSSHTunnel",
  "/vpn_service.v1.VPNService/Relay",
};

std::unique_ptr< VPNService::Stub> VPNService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< VPNService::Stub> stub(new VPNService::Stub(channel));
  return stub;
}

VPNService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_CreateVPNClient_(VPNService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_OpenSSHTunnel_(VPNService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Relay_(VPNService_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status VPNService::Stub::CreateVPNClient(::grpc::ClientContext* context, const ::vpn_service::v1::CreateVPNClientData& request, ::vpn_service::v1::CreateVPNClientDataAck* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_CreateVPNClient_, context, request, response);
}

void VPNService::Stub::experimental_async::CreateVPNClient(::grpc::ClientContext* context, const ::vpn_service::v1::CreateVPNClientData* request, ::vpn_service::v1::CreateVPNClientDataAck* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreateVPNClient_, context, request, response, std::move(f));
}

void VPNService::Stub::experimental_async::CreateVPNClient(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vpn_service::v1::CreateVPNClientDataAck* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreateVPNClient_, context, request, response, std::move(f));
}

void VPNService::Stub::experimental_async::CreateVPNClient(::grpc::ClientContext* context, const ::vpn_service::v1::CreateVPNClientData* request, ::vpn_service::v1::CreateVPNClientDataAck* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CreateVPNClient_, context, request, response, reactor);
}

void VPNService::Stub::experimental_async::CreateVPNClient(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vpn_service::v1::CreateVPNClientDataAck* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CreateVPNClient_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vpn_service::v1::CreateVPNClientDataAck>* VPNService::Stub::AsyncCreateVPNClientRaw(::grpc::ClientContext* context, const ::vpn_service::v1::CreateVPNClientData& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vpn_service::v1::CreateVPNClientDataAck>::Create(channel_.get(), cq, rpcmethod_CreateVPNClient_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::vpn_service::v1::CreateVPNClientDataAck>* VPNService::Stub::PrepareAsyncCreateVPNClientRaw(::grpc::ClientContext* context, const ::vpn_service::v1::CreateVPNClientData& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vpn_service::v1::CreateVPNClientDataAck>::Create(channel_.get(), cq, rpcmethod_CreateVPNClient_, context, request, false);
}

::grpc::Status VPNService::Stub::OpenSSHTunnel(::grpc::ClientContext* context, const ::vpn_service::v1::OpenSSHTunnelData& request, ::vpn_service::v1::OpenSSHTunnelDataAck* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_OpenSSHTunnel_, context, request, response);
}

void VPNService::Stub::experimental_async::OpenSSHTunnel(::grpc::ClientContext* context, const ::vpn_service::v1::OpenSSHTunnelData* request, ::vpn_service::v1::OpenSSHTunnelDataAck* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_OpenSSHTunnel_, context, request, response, std::move(f));
}

void VPNService::Stub::experimental_async::OpenSSHTunnel(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vpn_service::v1::OpenSSHTunnelDataAck* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_OpenSSHTunnel_, context, request, response, std::move(f));
}

void VPNService::Stub::experimental_async::OpenSSHTunnel(::grpc::ClientContext* context, const ::vpn_service::v1::OpenSSHTunnelData* request, ::vpn_service::v1::OpenSSHTunnelDataAck* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_OpenSSHTunnel_, context, request, response, reactor);
}

void VPNService::Stub::experimental_async::OpenSSHTunnel(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vpn_service::v1::OpenSSHTunnelDataAck* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_OpenSSHTunnel_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vpn_service::v1::OpenSSHTunnelDataAck>* VPNService::Stub::AsyncOpenSSHTunnelRaw(::grpc::ClientContext* context, const ::vpn_service::v1::OpenSSHTunnelData& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vpn_service::v1::OpenSSHTunnelDataAck>::Create(channel_.get(), cq, rpcmethod_OpenSSHTunnel_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::vpn_service::v1::OpenSSHTunnelDataAck>* VPNService::Stub::PrepareAsyncOpenSSHTunnelRaw(::grpc::ClientContext* context, const ::vpn_service::v1::OpenSSHTunnelData& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vpn_service::v1::OpenSSHTunnelDataAck>::Create(channel_.get(), cq, rpcmethod_OpenSSHTunnel_, context, request, false);
}

::grpc::Status VPNService::Stub::Relay(::grpc::ClientContext* context, const ::vpn_service::v1::RelayData& request, ::vpn_service::v1::RelayDataAck* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Relay_, context, request, response);
}

void VPNService::Stub::experimental_async::Relay(::grpc::ClientContext* context, const ::vpn_service::v1::RelayData* request, ::vpn_service::v1::RelayDataAck* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Relay_, context, request, response, std::move(f));
}

void VPNService::Stub::experimental_async::Relay(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vpn_service::v1::RelayDataAck* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Relay_, context, request, response, std::move(f));
}

void VPNService::Stub::experimental_async::Relay(::grpc::ClientContext* context, const ::vpn_service::v1::RelayData* request, ::vpn_service::v1::RelayDataAck* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Relay_, context, request, response, reactor);
}

void VPNService::Stub::experimental_async::Relay(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vpn_service::v1::RelayDataAck* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Relay_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vpn_service::v1::RelayDataAck>* VPNService::Stub::AsyncRelayRaw(::grpc::ClientContext* context, const ::vpn_service::v1::RelayData& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vpn_service::v1::RelayDataAck>::Create(channel_.get(), cq, rpcmethod_Relay_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::vpn_service::v1::RelayDataAck>* VPNService::Stub::PrepareAsyncRelayRaw(::grpc::ClientContext* context, const ::vpn_service::v1::RelayData& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vpn_service::v1::RelayDataAck>::Create(channel_.get(), cq, rpcmethod_Relay_, context, request, false);
}

VPNService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VPNService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VPNService::Service, ::vpn_service::v1::CreateVPNClientData, ::vpn_service::v1::CreateVPNClientDataAck>(
          [](VPNService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::vpn_service::v1::CreateVPNClientData* req,
             ::vpn_service::v1::CreateVPNClientDataAck* resp) {
               return service->CreateVPNClient(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VPNService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VPNService::Service, ::vpn_service::v1::OpenSSHTunnelData, ::vpn_service::v1::OpenSSHTunnelDataAck>(
          [](VPNService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::vpn_service::v1::OpenSSHTunnelData* req,
             ::vpn_service::v1::OpenSSHTunnelDataAck* resp) {
               return service->OpenSSHTunnel(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VPNService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VPNService::Service, ::vpn_service::v1::RelayData, ::vpn_service::v1::RelayDataAck>(
          [](VPNService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::vpn_service::v1::RelayData* req,
             ::vpn_service::v1::RelayDataAck* resp) {
               return service->Relay(ctx, req, resp);
             }, this)));
}

VPNService::Service::~Service() {
}

::grpc::Status VPNService::Service::CreateVPNClient(::grpc::ServerContext* context, const ::vpn_service::v1::CreateVPNClientData* request, ::vpn_service::v1::CreateVPNClientDataAck* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VPNService::Service::OpenSSHTunnel(::grpc::ServerContext* context, const ::vpn_service::v1::OpenSSHTunnelData* request, ::vpn_service::v1::OpenSSHTunnelDataAck* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VPNService::Service::Relay(::grpc::ServerContext* context, const ::vpn_service::v1::RelayData* request, ::vpn_service::v1::RelayDataAck* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace vpn_service
}  // namespace v1

