/**
 * Shared styles for user modal components
 * Used by both UserCreateModal and UserEditModal
 */

export const modalStyles = {
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.75)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1300,
  },
  modalContainer: {
    width: "90%",
    maxWidth: "900px",
    maxHeight: "90vh",
    backgroundColor: "#1A1A1A",
    borderRadius: "16px",
    border: "1px solid rgba(255,255,255,0.12)",
    color: "#fff",
    boxShadow: "0 25px 60px rgba(0,0,0,0.6)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  header: {
    padding: "24px 32px",
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    borderBottom: "1px solid rgba(255,255,255,0.08)",
    flexShrink: 0,
  },
  title: {
    fontSize: "1.3rem",
    fontWeight: 600,
    marginBottom: "4px",
  },
  closeButton: {
    background: "none",
    border: "none",
    color: "#fff",
    fontSize: "28px",
    cursor: "pointer",
    padding: "0",
    width: "32px",
    height: "32px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "8px",
    transition: "background-color 0.2s",
    marginTop: "-4px",
  },
  content: {
    padding: "24px 32px",
    overflowY: "auto",
    flex: 1,
    minHeight: "400px",
  },
  stepContent: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
  },
  formGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  label: {
    fontSize: "0.875rem",
    color: "rgba(255,255,255,0.7)",
    fontWeight: 500,
  },
  input: {
    backgroundColor: "#111",
    border: "1px solid rgba(255,255,255,0.12)",
    borderRadius: "10px",
    padding: "12px 16px",
    color: "#fff",
    fontSize: "0.9rem",
    outline: "none",
    transition: "all 0.2s",
  },
  assignedSection: {
    marginTop: "8px",
  },
  assignedLabel: {
    fontSize: "0.875rem",
    color: "rgba(255,255,255,0.7)",
    fontWeight: 500,
    marginBottom: "12px",
  },
  cardsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(160px, 1fr))",
    gap: "12px",
  },
  footer: {
    borderTop: "1px solid rgba(255,255,255,0.12)",
    padding: "20px 32px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexShrink: 0,
  },
  footerLeft: {
    display: "flex",
  },
  footerRight: {
    display: "flex",
    gap: "12px",
  },
  backButton: {
    background: "transparent",
    border: "1px solid rgba(255,255,255,0.18)",
    color: "#fff",
    padding: "10px 24px",
    borderRadius: "10px",
    cursor: "pointer",
    fontSize: "0.9rem",
    fontWeight: 500,
    transition: "all 0.2s",
  },
  nextButton: {
    background: "rgba(59,130,246,0.15)",
    border: "1px solid rgba(59,130,246,0.3)",
    color: "#3B82F6",
    padding: "10px 24px",
    borderRadius: "10px",
    cursor: "pointer",
    fontSize: "0.9rem",
    fontWeight: 600,
    transition: "all 0.2s",
  },
  deleteButton: {
    background: "rgba(220,38,38,0.15)",
    border: "1px solid rgba(220,38,38,0.3)",
    color: "#DC2626",
    padding: "10px 24px",
    borderRadius: "10px",
    cursor: "pointer",
    fontSize: "0.9rem",
    fontWeight: 600,
    transition: "all 0.2s",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  updateButton: {
    background: "rgba(59,130,246,0.15)",
    border: "1px solid rgba(59,130,246,0.3)",
    color: "#3B82F6",
    padding: "10px 24px",
    borderRadius: "10px",
    cursor: "pointer",
    fontSize: "0.9rem",
    fontWeight: 600,
    transition: "all 0.2s",
  },
  disabledButton: {
    opacity: 0.4,
    cursor: "not-allowed",
  },
};
